projen/projen

lib/node-project.ts

support keywords

---

.github/workflows/build.yml
.github/workflows/release.yml
lib/node-project.ts

feat: anti-tamper

---

API.md
src/node-project.ts
src/project.ts
src/version.ts

- `Version.current()` tried to create a new file without ensuring `project.outdir` existed.
- Small fix for custom .gitignore / .npmignore entries
- Added some docstrings

fix(core): version / custom outdir

---

.projenrc.js
API.md
package.json
src/_resolve.ts
src/component.ts
src/dependabot.ts
src/eslint.ts
src/file.ts
src/github-workflow.ts
src/ignore-file.ts
src/index.ts
src/inventory.ts
src/jest.ts
src/jsii-docgen.ts
src/jsii-project.ts
src/json.test.ts
src/json.ts
src/license.ts
src/mergify.ts
src/node-project.ts
src/project.ts
src/projen-upgrade.ts
src/typescript-typedoc.ts
src/typescript.ts
src/version.ts
src/yaml.ts
test/__snapshots__/inventory.test.ts.snap
test/resolve.test.ts
yarn.lock

As much as it's romantic, it didn't add much value to this project.
Implement a simple decentralized synthesis model where "Component" has a "synthesize" method
that accepts an output directory and can emit files into that directory.

feat: do not depend on "constructs"

---

src/node-project.ts

fix(core): peerDependencyOptions not passed correctly
Closes: #53 

fix(core): peerDependencyOptions not passed

---

license-text/MIT.txt

feat: add MIT license

---

.github/workflows/release.yml
src/jsii-project.ts

feat: upgrade download-artifact action to 2.0.1

---

API.md
src/node-project.ts

fix(node): typo in addScript docstring

---

README.md

*Issue #, if available:*
The steps to bootstrap projen were recently changed.

docs: updating contribution steps

---

API.md
src/node-project.ts
test/__snapshots__/inventory.test.ts.snap

fix(node): typo in help-text

---

README.md

the package name should be the same throughout the sample

chore: fix readme for external project types

---

src/react.ts

*Issue #, if available:* N/A
*Description of changes:* Fix currently failing build caused by merging of #228 and #229 to master
Also fixed categorization of some commands

fix(react): build error caused by API change

---

src/cli/cmds/new.ts

Fixes #280 
* Makes a fix to the cli `new` renderParams. It was not properly outputting an array param

fix/280-Render params changes for the comments broke the new --from method

---

src/awscdk-app-ts.ts

See https://github.com/aws/aws-cdk/pull/11470

feat: prefer ts files for ts-node

---

.gitignore
API.md
package.json
src/jest.ts
yarn.lock

First stab at the least opinionated implementation.
A possible next step would be a dedicated, opinionated JestJUnit config object
Fixes #278

feat(jest): test results processing

---

src/cdk8s-construct.ts
test/__snapshots__/inventory.test.ts.snap
test/__snapshots__/new.test.ts.snap

https://github.com/awslabs/cdk8s/blob/master/CHANGELOG.md#100-beta1-2020-11-18
Fixes #327

fix(cdk8s-construct): converts cdk8s-plus to cdk8s-plus-17 AND bumps constructs

---

src/cli/macros.ts

fix: project setup fails when git config is not set

---

.github/workflows/rebuild-bot.yml
src/node-project.ts

The commit command did not include `-a`

fix(node): rebuild-bot did not commit files

---

src/node-project.ts
src/project.ts
src/util.ts
test/util.test.ts

fix(node): CI always evaluated as true

---

API.md
package.json
yarn.lock

Upgrades jsii-docgen and adds missing docs.

chore: upgrade jsii-docgen

---

src/tasks/runtime.ts

fix(tasks): logs of task execution are no longer printed

---

test/__snapshots__/integ.test.ts.snap
test/integ.test.ts
test/integration/cdk8s/cdk8s.common.js

chore: fix - integ tests in subdirectories did not execute

---

.mergify.yml
.projenrc.js

Thus mergify will not auto-merge this.

chore: dont auto merge core pull requests

---

API.md
src/tasks/task.ts
test/tasks/tasks.test.ts

Allow to prepend not only exec tasks but also spawn and say tasks.

feat(task): additional prepend methods

---

src/cli/cmds/start.ts

feat: make `projen start` interactive by default

---

src/project.ts
test/subproject.test.ts

fix: subproject generated files are deleted too early

---

API.md
src/jest.ts
test/__snapshots__/integ.test.ts.snap
test/jest.test.ts

Allow adding test match patterns to jest.
---

feat(jest): addTestMatch()

---

src/cli/cmds/new.ts

Looking towards supporting multiple languages for projenrc, we need to give more control to the project classes (over the cli) when it comes to bootstrapping new projects.
This changes how `new` is implemented such that synthesis is performed by calling `.synth()` on a project object, and not by using the CLI's synth code path, which is tailored for the javascript version of .projenrc.
For example, it will now be possible to implement a `JavaProject` which will synthesize a java directory structure and a manifest that will take a java dependency on "projen" from maven. It will also be configured to read the projenrc from a java file within the source tree.
This solves the bootstrapping problem for compiled languages: if projenrc need to be compiled in order to be synthesized, we will need …

feat(cli): improved bootstrapping

---

API.md
src/jest.ts

Fix bug in jest collectCoverageFrom type

---

package.json
yarn.lock

chore: upgrade yargs

---

src/__tests__/util.test.ts
src/util.ts

fix: synthesizing react subproject fails due to stack overflow

---

API.md
src/__tests__/jsii.test.ts
src/publisher.ts

---
fix: #606
add MAVEN_ENDPOINT

feat(publishToMaven): add MAVEN_ENDPOINT (#606)

---

.projenrc.js
package.json

Updating package description (and testing mutable builds along the way)
---

chore: update description

---

.projen/deps.json
.projenrc.js
API.md
package.json
src/__tests__/ini.test.ts
src/index.ts
src/ini.ts
yarn.lock

feat: IniFile component

---

src/web/next.ts

if options tailwind: true wasn't present tailwind was off

fix(nextjs): honor the default of tailwind: true

---

src/web/next.ts

feat(nextjs): adds `export` to out/ directory

---

.github/workflows/release.yml
API.md
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/__snapshots__/inventory.test.ts.snap
src/__tests__/__snapshots__/jsii.test.ts.snap
src/__tests__/__snapshots__/new.test.ts.snap
src/jsii-project.ts
src/node-project.ts

See https://github.com/aws/jsii/pull/2803
---

chore: temporarily install "gh" cli when running in superchain (until included)

---

API.md
src/__tests__/source-code.test.ts
src/index.ts
src/source-code.ts

Introduce a simple `SourceCode` component which offers simple APIs for generating source files.
Example:
```ts
const code = new SourceCode(project, 'source.ts');
code.line('// this is my source code');
code.open('export class Foo {');
code.open('public run() {');
code.line('console.log("running");');
code.close('}'); // method run
code.close('}'); // class Foo
```
---

feat: source code component

---

.github/workflows/build.yml
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/__snapshots__/node-project.test.ts.snap
src/node-project.ts

The `git commit -am` command only adds modified files, not new files. Replace it with `git add . && git commit -m`.
Fixes #752
---

fix(build): new files not added by self-mutation

---

src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
src/__tests__/web/__snapshots__/react-project.test.ts.snap
src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
src/__tests__/web/nextjs-project.test.ts
src/__tests__/web/nextjs-ts-project.test.ts
src/__tests__/web/react-project.test.ts
src/__tests__/web/react-ts-project.test.ts

Fixes an issue with #713. Should have caught this before - my bad.
---

chore(web): fix non-determinism in snapshot tests

---

.npmignore
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/__snapshots__/new.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
src/typescript.ts
src/version.ts

Add bump-related files and tsbuildinfo file.
---

feat: add some files to npmignore

---

.projen/tasks.json
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
src/__tests__/web/__snapshots__/react-project.test.ts.snap
src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
src/version.ts

The pattern is not a value of the `--list` switch
---

chore: fix git tag command

---

.projen/tasks.json
src/__tests__/__snapshots__/new.test.ts.snap
yarn.lock

See https://github.com/advisories/GHSA-f2jv-r9rf-7988
---

chore: upgrade deps (CVE-2021-23369)

---

API.md
src/javascript/index.ts
src/javascript/npm-config.ts

fix: missing export of NpmConfig

---

src/github/workflows-model.ts
src/release/release.ts

Reorganize the code so that there is a single flow of steps instead of the convoluted structure from the previous pull request.
Workflows did not change.
---

chore(release): refactor workflow code

---

.github/workflows/upgrade-dependencies.yml
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/__snapshots__/upgrade-dependencies.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
src/__tests__/web/__snapshots__/react-project.test.ts.snap
src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
src/upgrade-dependencies.ts

Download the patchfile into a temporary directory.
---

fix(deps): patchfile added to deps pull request

---

src/__tests__/release/__snapshots__/release.test.ts.snap
src/__tests__/util.ts

Do not use version numbers when executing projen.
---

chore: make runTaskCommand deterministic in tests

---

src/tasks/runtime.ts

Just a QOL improvement I thought might be helpful.
---

feat: display a message if no actions are run for a task

---

src/__tests__/github/__snapshots__/auto-approve.test.ts.snap
src/github/auto-approve.ts

minor fix on the auto-approve workflow condition.
Fixes: #860 
---

fix(auto-approve): invalid condition

---

src/cli/cmds/new.ts

fix(projen new): git commit is broken on windows

---

API.md
src/__tests__/release/__snapshots__/release.test.ts.snap
src/publisher.ts

Also add some documentation on how to publish to GitHub packages.
---

feat(npm github packages): default to GITHUB_TOKEN

---

src/__tests__/__snapshots__/new.test.ts.snap
src/__tests__/new.test.ts
src/cli/cmds/new.ts
src/java/projenrc.ts
src/javascript/render-options.ts
src/python/projenrc.ts

fix(cli): new from external module with multiple types

---

README.md
src/__tests__/__snapshots__/new.test.ts.snap

chore: update docs to indicate manual releases are broken

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-dependencies.yml
src/__tests__/__snapshots__/integ.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
src/node-project.ts

Upgrade to `actions/setup-node@v2.2.0`
---

feat: upgrade setup-node to v2.2.0

---

SECURITY.md
src/__tests__/__snapshots__/new.test.ts.snap

Per GitHub's recommendation
---

chore: add SECURITY.md

---

README.md
src/__tests__/__snapshots__/inventory.test.ts.snap
src/inventory.ts

fix break links of currently supported project types in ## Getting Started
---

fix: change break links to API.md

---

src/__tests__/java/__snapshots__/java-project.test.ts.snap
src/__tests__/java/java-project.test.ts
src/__tests__/util.ts

Resolves a bug running integration tests on macOS introduced in #963.
---

fix: integration test errors on macOS

---

API.md
docs/tasks.md
src/node-project.ts

docs: remove outdated references to NpmTaskExecution

---

docs/releases.md

chore: add minimal release documentation

---

.github/workflows/release.yml
.projen/tasks.json
.projenrc.js
package.json
src/__tests__/__snapshots__/new.test.ts.snap
src/__tests__/java/__snapshots__/java-project.test.ts.snap
src/__tests__/java/__snapshots__/projenrc.test.ts.snap

Migrate projen to publish with cdklabs accounts.
---

chore: publish using cdklabs accounts

---

CONTRIBUTING.md

Add a recording from a meeting in which we walked through some of the projen code base. It provides some initial orientation for contributors.
---

feat(contributors): codebase walkthrough video

---

.all-contributorsrc
README.md

chore: update contributors

---

src/cdktf-construct.ts

bump constructs to v10 for cdktf

---

API.md
src/__tests__/java/__snapshots__/java-project.test.ts.snap
src/__tests__/java/__snapshots__/projenrc.test.ts.snap
src/__tests__/jsii.test.ts
src/awscdk-construct.ts
src/java/projenrc.ts

fix: outdated Java group ID for projen

---

src/release/update-changelog.task.ts

Missed an environment variable rename.
https://github.com/projen/projen/pull/1047#issuecomment-933883743
---

fix(release): update changelog task env var

---

.projen/deps.json
.projen/tasks.json
.projenrc.js
API.md
package.json
src/release/bump-version.task.ts
src/release/bump-version.ts
src/release/release.ts
src/version.ts
test/__snapshots__/inventory.test.ts.snap
test/release/bump.test.ts
yarn.lock

allows to use changelog easily with repos not in public GitHub
fixes #1204
---

feat: allow customization of versionrc file

---

src/awscdk/lambda-function.ts

fix: lambdas are now produced with posix paths only

---

.projenrc.js
package.json

chore: add NPM keywords for projen

---

src/cli/synth.ts

chore: improve error output for projen synth

---

.github/workflows/release.yml
src/release/publisher.ts
test/__snapshots__/integ.test.ts.snap
test/release/__snapshots__/release.test.ts.snap

chore: fix Python version in release workflow

---

src/cli/cmds/new.ts

This PR supercedes https://github.com/projen/projen/pull/1437.  Since all changes were to one file and the main branch had undergone significant changes while this was in flight, I close 1437 and created this new PR off the new main to keep the change set extremely understandable and easy (and so I didn't mess up any merge corrections in code I am not familiar with).
git prior to v2.28 does not directly support the "init -b" option, requiring the former commands in that scenario.  Ubuntu 20.04 still uses v2.25 and is a very common distro version since it is LTS so this fix is quite applicable.
---

new code to handle older git that does not do 'init -b' command

---

.github/workflows/auto-approve.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/stale.yml
.github/workflows/upgrade-main.yml
.projen/deps.json
.projenrc.js
API.md
package.json
src/yaml.ts
test/__snapshots__/integ.test.ts.snap
test/__snapshots__/upgrade-dependencies.test.ts.snap
test/cdk/__snapshots__/jsii.test.ts.snap
test/github/__snapshots__/auto-approve.test.ts.snap
test/github/__snapshots__/stale.test.ts.snap
test/java/__snapshots__/java-project.test.ts.snap
test/java/__snapshots__/projenrc.test.ts.snap
test/json/__snapshots__/projenrc.test.ts.snap
test/python/__snapshots__/poetry.test.ts.snap
test/python/__snapshots__/projenrc.test.ts.snap
test/python/__snapshots__/python-project.test.ts.snap
test/release/__snapshots__/release.test.ts.snap
test/web/__snapshots__/nextjs-project.test.ts.snap
test/web/__snapshots__/nextjs-ts-project.test.ts.snap
test/web/__snapshots__/react-project.test.ts.snap
test/web/__snapshots__/react-ts-project.test.ts.snap
yarn.lock

Upgrade the bundled `yaml` dependency to `yaml@2` and disable line folding by default (can be changed through `YamlFile.lineWidth`.
---

chore: disable yaml folding

---

API.md
src/cdk8s/cdk8s-construct.ts
test/__snapshots__/inventory.test.ts.snap
test/__snapshots__/new.test.ts.snap
test/cdk8s-construct.test.ts

feat(cdk8s): constructs version inference

---

README.md
src/inventory.ts
test/__snapshots__/inventory.test.ts.snap

chore: update README links to point to docs site

---

docs/CNAME

chore: add CNAME file

---

src/github/workflows-model.ts

- workflows to trigger on
- branches or branches-ignore to limit on
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
---

feat(github): add workflow run options

---

docs/github.md

chore: stub GitHub docs

---

README.md
docs/README.md
docs/github.md
src/inventory.ts
test/__snapshots__/inventory.test.ts.snap

Small error. Also fixing a broken link
---

fix: missing item in docs table of contents

---

src/javascript/node-project.ts
test/__snapshots__/node-project.test.ts.snap

fix: mutable should be optional and not always true for render workflow

---

README.md

fix: grammar

---

docs/api/API.md
src/awscdk/awscdk-app-java.ts
src/awscdk/awscdk-app-py.ts
src/awscdk/awscdk-app-ts.ts
src/source-code.ts
test/awscdk/python-app.test.ts

feat(awscdk-app): initialize sample code stack names based on project name

---

README.md

chore: list GitHub Action project in README

---

src/javascript/node-package.ts
test/javascript/node-package.test.ts

fix: local dependencies using `file:` prefix

---

src/cdk/jsii-project.ts

fix(jsii-project): publish to NPM for the jsii project will respect codeArtifactOptions

---

docs/api/API.md
src/awscdk/auto-discover.ts
src/awscdk/awscdk-app-ts.ts
src/awscdk/awscdk-construct.ts
test/__snapshots__/inventory.test.ts.snap

chore(awscdk): enable Edge Lambda auto discover

---

docs/api/API.md
src/circleci/model.ts

fix(circleci): fix typo on workflow job filter

---

.projen/deps.json
.projen/tasks.json
docs/api/API.md
package.json
src/javascript/jest.ts
src/typescript/typescript.ts
test/__snapshots__/integ.test.ts.snap
test/javascript/__snapshots__/node-project.test.ts.snap
test/javascript/node-project.test.ts
test/javascript/upgrade-dependencies.test.ts
yarn.lock

fix: Pin jest dependencies to same version

---

src/typescript/typescript.ts
test/typescript/__snapshots__/typescript.test.ts.snap

fix(typescript): ignore declaration map files from git

---

docs/typescript.md

I added a section which details the steps needed to upgrade a project previously created with a .projenrc.js file to the new .projenrc.ts file.
---

feat: adding steps for upgrading project to .ts file

---

src/task-runtime.ts

feat: add support for `cp` command on Windows using shx

---

src/awscdk/awscdk-app-py.ts
src/cdk8s/cdk8s-app-py.ts
test/awscdk/awscdk-app.test.ts
test/awscdk/python-app.test.ts
test/cdk8s/cdk8s-app-project-py.test.ts
test/cdk8s/cdk8s-app-project-ts.test.ts

fix: python project dependencies when running Jest Test

---

docs/api/API.md
src/vscode/extensions.ts
src/vscode/index.ts
src/vscode/vscode.ts
test/vscode/extensions.test.ts

feat(vscode): support workspace recommended extensions

---

docs/api/API.md
src/cdk/jsii-project.ts
test/__snapshots__/inventory.test.ts.snap
test/cdk/jsii.test.ts

feat(jsii-project): add support for compressing assembly file

---

src/javascript/node-project.ts
test/__snapshots__/integ.test.ts.snap

Version 6 of PNPM is no loger maintained, so upgraded
https://pnpm.io/6.x/motivation
---

feat(PNPM): Updated to latest version

---

src/cdk/jsii-project.ts
test/cdk/jsii.test.ts

Fixes: #2078
Add pnpm/action-setup step into jsii-project prePublishSteps.
---

fix(release): publish to npm workflow fails when set project package manager to PNPM

---

test/javascript/node-project.test.ts

chore: fix typos in node-project tests

---

.projen/deps.json
package.json
src/javascript/upgrade-dependencies.ts
test/__snapshots__/integ.test.ts.snap
test/cdk/__snapshots__/jsii.test.ts.snap
test/javascript/__snapshots__/node-project.test.ts.snap
test/typescript/__snapshots__/typescript.test.ts.snap
test/web/__snapshots__/nextjs-project.test.ts.snap
test/web/__snapshots__/nextjs-ts-project.test.ts.snap
test/web/__snapshots__/react-project.test.ts.snap
test/web/__snapshots__/react-ts-project.test.ts.snap
yarn.lock

chore: upgrade npm-check-updates to v16

---

src/cdktf/cdktf-construct.ts
test/__snapshots__/inventory.test.ts.snap
test/__snapshots__/new.test.ts.snap

chore: bump default version of cdktf construct

---

docs/api/API.md
src/javascript/bundler.ts
test/javascript/bundler.test.ts

feat: made bundler esbuild loaders configurable (#2181)

---

src/release/reset-version.task.ts

fix(node): add newline to package.json on release

---

README.md
docs/github.md

chore(github): document fine-grained personal access tokens (beta) & clarify docs for classic personal access tokens

---

.github/workflows/pull-request-lint.yml
src/github/pull-request-lint.ts
test/__snapshots__/integ.test.ts.snap
test/__snapshots__/new.test.ts.snap
test/cdk/__snapshots__/jsii.test.ts.snap
test/github/__snapshots__/pull-request-lint.test.ts.snap
test/java/__snapshots__/java-project.test.ts.snap
test/java/__snapshots__/projenrc.test.ts.snap
test/json/__snapshots__/projenrc.test.ts.snap
test/python/__snapshots__/poetry.test.ts.snap
test/python/__snapshots__/projenrc.test.ts.snap
test/python/__snapshots__/python-project.test.ts.snap
test/release/__snapshots__/release.test.ts.snap
test/typescript/__snapshots__/typescript.test.ts.snap
test/web/__snapshots__/nextjs-project.test.ts.snap
test/web/__snapshots__/nextjs-ts-project.test.ts.snap
test/web/__snapshots__/react-project.test.ts.snap
test/web/__snapshots__/react-ts-project.test.ts.snap

chore: update action to amannn/action-semantic-pull-request@v5.0.2
fixed #2254 
---

chore(github): update action to amannn/action-semantic-pull-request@v5.0.2

---

docs/api/API.md
src/javascript/jest.ts
test/javascript/jest.test.ts

fix(jest): new snapshots are added when updating snapshots is disabled

---

docs/awscdk-apps.md

Added possible implemenattion
---

chore(aws-cdk-app): Update documentation

---

docs/releases.md

chore: document prerelease option

---

src/javascript/bundler.ts

fix: use posix paths for lambda outfiles

---

docs/releases.md

I'm adding a little bit of text to help potential new users that want to understand better the versioning system of Projen.
---

chore(docs): update releases.md to add default tag prefix

---

src/cdk/jsii-project.ts
src/javascript/node-project.ts
test/__snapshots__/integ.test.ts.snap

First PR here, not sure how to test this except YOLO! It's a minor version bump, so not expecting anything exciting to happen.
fixes #2421 
---

chore(pnpm): bump pnpm/action-setup@v2.2.2 to pnpm/action-setup@v2.2.4

---

src/gitlab/configuration.ts
test/gitlab/configuration.test.ts

fix(gitlab): allow setting of variables from constructor

---

test/project.test.ts

These tests were skipped unintentionally.
---

chore: re-enable skipped project tests

---

docs/api/API.md
src/vscode/devcontainer.ts
test/vscode/devcontainer.test.ts

See: https://containers.dev/features
---

feat(vscode): support dev container features

---

src/file.ts
test/subproject.test.ts

fix(file): annotate generated in sub-project creates incorrect patterns

---

src/cdk/jsii-project.ts
src/cli/cmds/new.ts
src/inventory.ts
test/__snapshots__/inventory.test.ts.snap
test/__snapshots__/new.test.ts.snap
test/inventory.test.ts
test/new.test.ts

Introduces a new custom doctag `@pjnew` to force an initial value at project creating time.
This will allow us to change defaults we previously couldn't because the impact would be to complicated.
---

feat(jsii): new `JsiiProject`s default to version `~5.0.0`

---

SECURITY.md

The section that explained how to report security vulnerabilities only contained the template blurb.
---

chore: explain how to report security vulnerabilities

---

docs/api/API.md
src/project.ts

feat(project): public subprojects property

---

license-text/AGPL-3.0-or-later.txt

Retrieved from https://choosealicense.com/licenses/agpl-3.0/
---

feat(license): add AGPL-3.0-or-later

---

docs/api/API.md
src/docker-compose/docker-compose-render.ts
src/docker-compose/docker-compose-service.ts
test/docker-compose/docker-compose.test.ts
yarn.lock

Resolves https://github.com/projen/projen/issues/2867
---

feat(docker): suport platform in docker-compose

---

docs/api/API.md
src/cdk8s/cdk8s-deps.ts
test/__snapshots__/inventory.test.ts.snap

chore: fix typo in API.md

---

docs/java.md
license-text/EUPL-1.2.txt
rfcs/github-project-settings.md

chore: fix various documentation typos

---

README.md

Fixed minor grammatical error
---

chore(docs): fix grammar in README.md

---

src/python/python-project.ts
test/python/python-project.test.ts

fix(python): honour sample option for pytest sample code

---

README.md
src/inventory.ts
test/__snapshots__/inventory.test.ts.snap

chore(docs): fix links in `README.md` have wrong hash property

---

src/awscdk/lambda-function.ts
test/awscdk/lambda-function.test.ts

feat(awscdk): Node.js 20.x runtime

---

src/build/build-workflow.ts
src/github/index.ts
src/github/task-workflow.ts
src/github/workflow-actions.ts
src/github/workflow-jobs.ts
src/github/workflow-steps.ts
src/javascript/upgrade-dependencies.ts
src/release/release.ts
src/util/object.ts
test/__snapshots__/integ.test.ts.snap
test/util/object.test.ts
test/web/__snapshots__/nextjs-ts-project.test.ts.snap
test/web/__snapshots__/react-ts-project.test.ts.snap

Fixes https://github.com/projen/projen/issues/3203
Placed a bit of an opinion on WorkflowSteps with a common interface, please weigh in on how you like the pattern.  I moved an unrelated Step to the new interface in order to demonstrate.
This is non-breaking PR, but does include a deprecation, since I moved something.
---

fix: WorkflowSteps enables completely consistent actions/checkout and setGitIdentity in Workflows

---

src/typescript/typescript.ts
test/typescript/typescript.test.ts

Fixes https://github.com/projen/projen/issues/3224
---

fix(jest): ts-jest configuration spelling mistakes

---

docs/api/javascript.md
src/javascript/jest.ts
test/javascript/jest.test.ts

Dependency of https://github.com/projen/projen/issues/3283
---

feat(jest): addModuleNameMappers, addModulePaths, addRoots

---

docs/api/javascript.md
src/javascript/typescript-config.ts

Fixes https://github.com/projen/projen/issues/3312
---

feat(tsconfig): downlevelIteration, incremental, tsBuildInfoFile added to compilerOptions

---

.projen/deps.json
.projenrc.ts
package.json
yarn.lock

feat: upgrade jsii to 5.3

---

docs/api/github.md
src/github/github-credentials.ts

The old page was moved and leads to a 404
---

chore(github): docs URL for GitHub App config

---

.projen/deps.json
.projenrc.ts
package.json
yarn.lock

fix: upgrade TypeScript and jsii to v5.4

---

.github/workflows/build.yml
.github/workflows/release.yml
src/github/workflows.ts
test/__snapshots__/integ.test.ts.snap
test/cdk/__snapshots__/jsii.test.ts.snap
test/release/__snapshots__/release.test.ts.snap

Resolves runtime deprecation warnings.
---

fix(github): bump version of actions/setup-java to v4

---

docs/api/javascript.md
src/javascript/typescript-config.ts

Fixes https://github.com/projen/projen/issues/3603
---

fix(typescript): typeRoots is missing in typescript config

---

docs/api/javascript.md
src/javascript/typescript-config.ts

Fixes https://github.com/projen/projen/issues/3612
---

fix(typescript): add moduleDetection to typescript config

---

docs/api/javascript.md
src/javascript/typescript-config.ts
test/javascript/typescript-config.test.ts

Fixes https://github.com/projen/projen/issues/3634
---

feat(typescript): tsconfig can now add/remove include/excludes

---

src/version.ts
test/version.test.ts

Fixes https://github.com/projen/projen/issues/3492
---

fix(version): bump and unbump tasks env no longer clobber each other

---

docs/api/javascript.md
src/javascript/jest.ts
test/javascript/jest.test.ts

feat(jest): make passWithNoTests configurable

---

test/python/python-project.test.ts

chore: pip extras explicit tests

---

docs/api/awscdk.md
src/awscdk/lambda-extension.ts
src/awscdk/lambda-function.ts
test/awscdk/__snapshots__/lambda-extension.test.ts.snap
test/awscdk/lambda-function.test.ts

feat(awscdk): support for lambda 22

---

.github/workflows/release.yml
.projenrc.ts
docs/api/cdk.md
docs/api/release.md
src/release/publisher.ts

Fixes failing builds and explains publishing to maven central a bit better.
---

chore: publish to Maven Central
