- API.md
- src/jsii-project.ts
- src/typescript-typedoc.ts
- src/typescript.ts
- src/version.ts
- tsconfig.jest.json
- Simple docgen via typedoc for TS projects
- Refactored the jsii-specific `tsconfig.jest.json` settings to live inside `jsii-project`
- compilerOptions interface
- `charset` is [deprecated](https://www.typescriptlang.org/tsconfig#charset)
- fix for the `mkdirSync` fix (now recursive)
BREAKING CHANGE: `options` is now required for `TypescriptConfig`.
> feat(ts): docgen / more docstrings

- package.json
- src/version.ts
- yarn.lock
Upgrading `standard-version` to `^9.0.0` ahead of a projen upgrade in [cdk8s](https://github.com/awslabs/cdk8s). Note that this upgrade [rules out support for NodeJS@8](https://github.com/conventional-changelog/standard-version/pull/612).
> chore: upgrade to standard-version 9.0.0

- src/typescript.ts
*Issue #132, if available:*
This adds the missing `/` in the default `types` path in `TypeScriptProject`
> fix(typescript): Add missing `/` to default types path 

- .eslintrc.json
- src/eslint.ts
For nested projects eslint fails because it parses all parent configs too.
By setting the root flag, eslint stops looking in parent directories.
> fix: eslint fails in nested projects

- README.md
*Issue #, if available:*
Yarn boostrap was used instead of bootstrap. 
boostrap -> bootstrap
Other **minor** typos.
> Update README - typo: "boostrap".

- .projenrc.js
- API.md
- package.json
- src/awscdk-app-ts.ts
- src/cli/cmds/start-app.ts
- src/eslint.ts
- src/jest.ts
- src/jsii-docgen.ts
- src/jsii-project.ts
- src/next.ts
- src/node-project.ts
- src/projen-upgrade.ts
- src/start.ts
- src/typescript-typedoc.ts
- src/typescript.ts
- src/version.ts
Add a `command` to each start menu entry in `package.json` and use it instead of assuming this is a yarn script. This opens the door for decoupling start menu from yarn/npm and allowing it to be used in other project types as an entry point.
This change also adds `ScriptOptions` to `node.addScript()` such that it is possible
to register a start menu entry together with adding scripts to the project.
Fixes #217
BREAKING CHANGE: `node.addScript(script, command)` now takes a single command instead of variable arguments. Use `node.addScript(script, [s1,s2].join(' && '))` to build a command from multiple statements.
> fix: start menu does not respect package manager

- .projenrc.js
- API.md
- README.md
- package.json
- src/awscdk-construct.ts
- src/dependabot.ts
- src/inventory.ts
- src/jest.ts
- src/jsii-project.ts
- src/node-project.ts
- src/projen-upgrade.ts
- src/typescript.ts
- src/yaml.ts
- test/__snapshots__/inventory.test.ts.snap
- chore: moves `eladb/projen` -> `projen/projen`, fixes spelling for src/ and test/ ; ignores CHANGELOG.md
> chore: moves eladb/projen -> projen/projen, fixes spelling

- API.md
- src/awscdk-app-ts.ts
- src/awscdk-construct.ts
- test/__snapshots__/inventory.test.ts.snap
- yarn.lock
Removes the use of the deprecate Semver class and old-style dependency methods.
> chore(cdk): remove deprecated Semver

- README.md
Hi! Here's a *very* small PR to update the "git clone" url in the readme since projen now seems to live at `projen/projen` instead of `eladb/projen`!
> docs(readme): clone url update

- src/cli/cmds/new.ts
- src/inventory.ts
Fixes #296 
* Alters inventory discovery to check for child directories for scoped packages
* #280 - sets the new project `additionalProps` to be `Record<string, string>` in order to be in line with the 280 bugfix change from yesterday
> fix(cli): "new --from" scoped packages is broken

- test/composite-project.test.ts
This should fix the build in master when bumping versions after #289. `NodeProject` in the tests wanted to pull the not-yet-released projen packages after the bump. This fix addresses the issue by changing the tests not to depend on any project type that needs to know Projen's version.
> fix: CompositeProject tests reference unreleased projen version after bump

- API.md
- src/index.ts
If you want to create Yaml Files in your custom modules you can't because projen hasn't exported the class. I just added the export and noticed that the `common.ts` is also not exported is there interest in exporting this also?
> fix: add missing yaml export

- test/node-project.test.ts
* Installing projen during tests fails while releasing
because yarn tries to install the to-be-released
version of projen
> test(license): do not install projen during test

- src/awscdk-app-ts.ts
This PR fixes syntax and linting errors in the starter code for `AwsCdkTypeScriptApp`.
> fix: cdk app starter test code syntax and linting errors

- src/github/github.ts
- src/project.ts
Since these are "global" services, their accessors will now be `undefined` in subprojects. This will allow subprojects to decide how to deal with things like workflows, IDE integration, etc.
> fix: github/vscode accessors should not be available in subprojects

- API.md
- src/awscdk-construct.ts
- test/__snapshots__/inventory.test.ts.snap
- test/__snapshots__/new.test.ts.snap
Description:
* docs/awscdk-construct.md mentions this parameter, however, it does not exist in the options
* there are significant cdk dependency issues if trying to support an older version of the cdk (e.g. `^1.67.0`) without pinned dependencies
> feat: Add version pinning option to construct project

- src/vscode/launch-config.ts
- test/vscode-launch-config.test.ts
As requested in https://github.com/projen/projen/pull/316#discussion_r536107141
> chore: add InternalConsoleOptions enum to VSCode launch config

- test/__snapshots__/integ.test.ts.snap
- test/docker-compose.test.ts
- test/gitpod.test.ts
- test/integ.test.ts
- test/integration/cdk-watchful.projenrc.js
- test/integration/cdk8s/cdk8s-cli.projenrc.js
- test/integration/cdk8s/cdk8s.common.js
- test/integration/cdk8s/cdk8s.projenrc.js
- test/jest.test.ts
- test/node-project.test.ts
- test/pr-template.test.ts
- test/util.ts
- test/vscode-launch-config.test.ts
Integration tests are a complete snapshot of the synthesis of real projects.
Ideally most of the coverage is achieved through unit tests, but this is a cheap way to capture unw
To add sample real projects, just add files with the `xxx.projenrc.js` extension under `test/integration`. If the file is in a subdirectory, the entire directory will be staged.
The `xxx.projenrc.js` file will be renamed `.projenrc.js` and the `projen` CLI will be executed. The resulting deep directory snapshot will be taken as a jest snapshot.
> chore: integration tests

- .projen/tasks.json
- API.md
- package.json
- src/node-project.ts
- src/typescript.ts
- test/__snapshots__/integ.test.ts.snap
jest does not perform any type-checking, so tests can pass but the code would have compilation errors.
This commit adds a test `test:compile` which runs `tsc --no-emit` against the test/** directory.
The task is spawned before running jest.
> feat(jest/typescript): `test:compile` task

- API.md
- src/github/auto-merge.ts
- src/github/index.ts
- src/node-project.ts
- test/__snapshots__/integ.test.ts.snap
Extract a `github.AutoMerge` component from `NodeProject`. This component will set up mergify to merge approved pull requests which pass CI builds.
> feat: auto-merge

- .eslintrc.json
- .projen/tasks.json
- API.md
- src/eslint.ts
- src/typescript.ts
- test/__snapshots__/eslint.test.ts.snap
- test/__snapshots__/integ.test.ts.snap
- test/eslint.test.ts
Allow specifying `devdirs` which is a list of directories that should be linted but also allow importing deps from `devDependencies`.
Previously these were hard-coded to `test` and `build-tools`.
---
> feat(eslint): devdirs

- .projenrc.js
- API.md
- package.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/jest.ts
- src/typescript.ts
Allow disabling the text output option for jest coverage to improve test output readability. This is okay in case coverage is collected and calculated through some other form.
This change also adds a "watch ignore pattern" for `src/**` when tests are executed from `lib/`.
Enable this for projen.
---
> feat(jest): coverage text output and watch ignore patterns

- src/__tests__/java/__snapshots__/maven.test.ts.snap
- src/java/junit.ts
This PR removes the usage of `...` causing the package name to be split into its characters when being processed by `path.join`. This would create `src/test/java/o/r/g/a/c/m/e` from `org.acme` in the sample package. 
Screenshot: 
---
> fix(java): corrupted java directory name

- src/project.ts
- src/util.ts
See https://github.com/aws/jsii/issues/2406 for details.
Until this is resolved in jsii, we bluntly hook `process.stdout.write()` and redirect the stream to STDERR. We do the same thing when we `exec()` shell commands.
NOTE: the task runtime still inherits STDOUT, so this applies only to logs coming from libraries.
---
> fix: output to STDOUT crashes jsii languages

- API.md
- src/__tests__/java/__snapshots__/pom.test.ts.snap
- src/__tests__/java/pom.test.ts
- src/deps/dependencies.ts
- src/deps/model.ts
- src/java/java-project.ts
- src/java/pom.ts
In maven, it is possible to specify dependencies that only apply to a specific plugin. This commit adds that capability.
NOTE: dependencies of plugins are not recorded in the project's dependency model at this point.
---
> feat(java): sub-dependencies for maven plugins

- API.md
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/jsii.test.ts
- src/jsii-project.ts
Adds `publishToGo` option to jsii projects which renders the `go` target in the jsii config. This will cause the build output to include a `dist/go` artifact that can then be published to a git repository.
Once `jsii-release` supports go, we need to add the relevant workflow steps to actually publish.
---
> feat(jsii): Golang support (without publishing yet)

- src/cli/index.ts
Closes #484
When you run a task that doesn't exist, it will now raise an error, showing the CLI help printout and the message "Unknown command: foobar" with the error code 1.
Existing functionality that I verified as left intact:
- if the invalid task name is similar to an existing task name, the CLI will still show the error message "Did you mean <name>?" (this is existing behavior provided by yargs)
- providing no task still runs the 'default' synthesis task
---
> fix(cli): error when the given task doesn't exist

- .github/workflows/rebuild-bot.yml
- .github/workflows/release.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/node-project.ts
When multiple commits are pushed to the main branch at once (for whatever reason), the release workflow will try to push both the new tag and the bump commit. In such a case, the tag will be pushed but the commit will fail, which means the repo is in a corrupted state (from a bump perspective).
This change fixes the broken transaction issue by pushing the tag only after the bump commit has been pushed.
The implication is that only the latest release (in the series of commits) will succeed. Ideally we'd want to cancel the release workflow (instead of failing it), but this will be done in a future change.
Fixes #553
---
> fix(node): tags may be pushed without a bump commit

- API.md
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/awscdk-construct.ts
Allows disabling the default behavior in which CDK dependencies are also added as normal dependencies (and not just peer dependencies).
Resolves #577
---
> feat(awscdk-construct): cdkDependenciesAsDeps

- .github/workflows/rebuild-bot.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/node-project.ts
To address a security issue, the `@projen rebuild` workflow will no longer be triggered by a comment on the pull request. This commit removes the `issue_comment` trigger from rebuild-bot workflow so that this workflow can only be executed manually by administrators.
Additional details will be provided at a future date.
---
> fix(node): security vulnerability in rebuild-bot

- src/cleanup.ts
The code that parses gitignore had some issues that caused some files not to be located by projen's cleanup command.
---
> fix(cleanup): some projen synthesized files are left orphaned

- API.md
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/node-project.ts
The NodeProject class expects a Semver object in `projenVersion`, but it's treated like a string, causing errors when stringifying to JSON files. I just corrected the type, which looks like it should be just string.
---
> fix(node-project): fix projenVersion type to correctly use a string

- .github/workflows/build.yml
- .github/workflows/release.yml
- .projen/tasks.json
- .projenrc.js
- API.md
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/__snapshots__/node-project.test.ts.snap
- src/__tests__/node-project.test.ts
- src/node-project.ts
- yarn.lock
By default, always run `projen` as part of the full-build task (called `build`). This applies both to local builds and CI builds.
This can be disabled by setting `projenDuringBuild` to `false` in (the rare case) you need to externally modify synthesized project files (e.g. when testing new projen features).
---
> feat(node): run "projen" as part of "build"

- src/__tests__/node-project.test.ts
- src/node-project.ts
#658 added the execution of "projen" as part of the full-build task. This works for top-level projects
but fails in subprojects.
Conditionally skip this for subprojects.
Fixes #661
---
> fix(node): subprojects fail to run "projen" as part of "build"

- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/awscdk-app-ts.ts
- src/awscdk-construct.ts
https://github.com/aws/aws-cdk/releases/tag/v1.95.2
https://github.com/advisories/GHSA-pch5-whg9-qr2r
Changes awscdk-app-ts, awscdk-construct to DEFAULT to `1.95.2` for the `cdkVersion`
> fix(deps): SECURITY: CVE-2021-28918, aws-cdk < 1.95.2 include this dependency

- src/web/postcss.ts
Fixes issue mentioned by @pgollucci 
---
> fix(nextjs): projen marker causes NextJS build warning

- src/web/next.ts
https://tailwindcss.com/docs/installation
tailwind css defaults to on and node.js 10x is EOL this month april 2021
so not conditionalizing it
> fix(nextjs): tailwind css requires Node.js 12.13.0+

- src/typescript-typedoc.ts
typedoc depends on marked which is what is actually vunlerable.
- https://github.com/TypeStrong/typedoc/commit/21fa828c7b62932a3666f67e961e569f1b6a1249
v2.0.0 includes the marked update to fix this.
Changes the 'docgen' flag to pull in typedocs@^2.
The default .projenrc.js config in projen/projen and that generated does
not enable this flag by default.
This can also be mitigated by setting `docgen: false` in .projenrc.js
if you are not in a position to upgrade.
https://nvd.nist.gov/vuln/detail/CVE-2021-21306
> fix(deps): SECURITY: CVE-2021-21306; force typedoc >= 2.0.0

- .github/workflows/release.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/node-project.ts
Since `dist/` may contain a large number of files (esp. for java), we decided to disable this feature for now.
---
> fix(release): unable to upload all files to release

- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/version.ts
We updated the configuration of standard-version to skip tagging (since the tag is created by the github release), so there is no need to delete the `v0.0.0` tag after we unbump anymore.
---
> fix: unbump fails since tag is not created

- .github/workflows/release.yml
- .gitignore
- .projen/tasks.json
- .versionrc.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/version.ts
The default for `standard-version` is to resolve the latest version tag globally across the repo.
Use a custom command (`git describe --abbrev=0 --tags`) to resolve the last tag from the current branch
instead of from across the entire repository.
---
> fix(release): invalid bump for projects with multiple release branches

- src/__tests__/util.ts
- src/cli/index.ts
- src/cli/synth.ts
If `--watch` (or `-w`) is specified when running `projen`, watch `projenrc.js` and re-synthesize upon change.
NOTE: This is currently only supported for projects that use the .js version of projenrc (i.e. not java).
---
> feat: projen --watch

- src/__tests__/__snapshots__/new.test.ts.snap
- src/cli/cmds/new.ts
This option is a hidden option used to support non-JavaScript project types (such as Java).
Simply skip it when producing `.projenrc.js`.
---
> fix: "jsiiFqn" is included in generated .projenrc.js file

- src/cli/synth.ts
If the project uses multiple files for projenrc, or non-javascript, then watch would not capture
any changes.
This change simply watches all changes in the project directory. This might have performance issues
for very large projects, so we may need to introduce some filters later.
---
> fix(--watch): watches only root .projenrc

- API.md
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/awscdk-construct.test.ts
- src/__tests__/util.ts
- src/awscdk-construct.ts
- src/cli/cmds/new.ts
CDK 2.0 pre-releases depend on constructs@10, and not constructs@3. This
selects the version of constructs to be registered based on the CDK major
version being used.
Additionally, a new `constructsVersion` option enables user-defined
versions to be used instead of the default/inferred version.
---
> fix(awscdk-lib): incorrect version of constructs used for CDK 2.0

- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/new.test.ts
- src/cli/cmds/new.ts
- src/inventory.ts
Fixes #748 
* Fixed the discovery of external types when resolving the project
* Fixed the `newProjectFromModule` directory handling
* Added a unit test for testing external packages - currently points to one of my packages because that's the one I had on hand
---
> fix: projen new not working with some of the new discovery changes

- API.md
- src/__tests__/__snapshots__/inventory.test.ts.snap
- src/__tests__/awscdk-app.test.ts
- src/awscdk-app-ts.ts
- src/awscdk-construct.ts
If `cdkVersion` is set to a version above 2.0.0, the project will use `aws-cdk-lib`, `constructs@^10` and the initial sample code will also be compatible with 2.0.
---
> feat(awscdk-app): CDK v2 support

- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/version.ts
If there are multiple version tags on the same commit, `git describe` would return the first tag which is lexicographically first. This is not what we want, so we now use `git tag` with a `version:refname` sort order in order to query the repo for the latest version (for real).
Fixes #762
---
> fix(bump): invalid version selected for multiple tags

- .github/workflows/build.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/node-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/node-project.ts
Add a condition that will only update status check if the build actually resulted in changes to the repo. This condition is added both for the "commit & push" step and the "update status" step. This means that we no longer
need the condition that only updates status checks if the PR is from a non-fork because if the push would have failed anyway and we would not get there at all.
Fixes #760
---
> fix(node): dependabot builds always fail

- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/version.ts
Fix #787 which tested if a version was not found, but then if there _was_ a version, it failed. AHHH!
---
> chore: bump fails if there is already a tag

- src/cli/cmds/start.ts
Fixes #771 
Interactive flag was missing boolean type. Without type, `npx projen start --interactive false` considers false as string and still runs in interactive mode.
---
> fix(cli): false value for interactive flag gets ignored in start command

- .github/workflows/build.yml
- .github/workflows/release.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/node-project.test.ts
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/github/workflows-model.ts
- src/github/workflows.ts
- src/node-project.ts
- src/publisher.ts
Make "permissions" a required property when defining a job to ensure workflows explicitly state their desired permissions. This allows them to run in GitHub repos that are configured in restricted mode.
Note that setting "write" permissions on the workflow does not mean that forks will get elevated access. Forks will always be restricted to "read" permissions according to [GitHub documentation] and manual validation.
Fixes #807
[GitHub documentation]: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
---
> fix(node): workflows fail if repo is in restricted mode

- .projen/tasks.json
- API.md
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/node-package.ts
- src/upgrade-dependencies.ts
Run `yarn install` immediately after `ncu` in order to make sure we get the correct version of `projen` before we actually run it.
Fixes #809
---
> fix(upgrade): projen upgrade workflow never upgrades projen

- .github/workflows/upgrade-dependencies.yml
- .projen/tasks.json
- API.md
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/upgrade-dependencies.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/node-project.ts
- src/upgrade-dependencies.ts
Allow specifying `pullRequestTitle` when creating a dependency upgrade workflow.
---
> feat(upgrade dependencies): improve pull request titles

- .all-contributorsrc
- .projen/tasks.json
- .projenrc.js
- README.md
I noticed there was an issue with the existing `contributors:update` script so I updated to handle the fact that the all-contributors check was returning a multi-part response:
```
Missing contributors in .all-contributorsrc:
dependabot[bot], mergify[bot], github-actions[bot], Hunter-Thompson, mmcculloh-dms, aisamu, iliapolo, Miradorn, kanatti, bracki, polothy, MrArnoldPalmer, neilkuan, pgarbe, smacintyre, tobias-bardino, yglcode
Unknown contributors found in .all-contributorsrc:
guan840912, gwriss
```
---
> chore: update contributors list

- src/cli/index.ts
Fixes #497
`yargs` provides a built-in utility that shows the script's version and immediately exits when the user passes the `--version` flag. Unfortunately, we are using `--version` as an field in new project types (so a user can run `projen new java --version 1.2.3` and the version will be pre-filled in their `projenrc` file), which causes a conflict. Currently, `yargs` doesn't provide ways to customize where this `--version` utility is valid (see https://github.com/yargs/yargs/issues/1918), so to work around this I manually implemented the `--version` feature so it only activates if you run `projen` with no subcommands.
Now the current behavior is:
```
$ projen --help
projen [command]
Commands:
projen new [PROJECT-TYPE] [OPTIONS]  Creates a new projen project
projen start …
```
> feat(cli): --version flag

- .github/workflows/release.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/release/release.ts
In order to create the github release, we need to know the version number but since we are reverting it
to 0.0.0, we need to store the bumped version somewhere.
---
> chore: copy package.json to backup in order to create the release

- API.md
- src/node-project.ts
Include `workflowBootstrapSteps` in all workflows.
---
> fix(node): workflowBootstrapSteps not respected

- .github/workflows/upgrade-dependencies.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/upgrade-dependencies.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/upgrade-dependencies.ts
Sometimes, the `runner.tmp` directory does not exist (e.g. when a custom container is used). Instead, just create it under cwd.
---
> fix(deps): unable to create patch file in custom containers

- src/__tests__/__snapshots__/integ.test.ts.snap
- src/node-project.ts
If `projenUpgradeSecret` is defined, use it for the normal dependency upgrade workflow and not just for the projen upgrade workflow. This is useful if dep changes require workflow changes
---
> feat(deps): use projen token for deps workflow if defined

- .github/workflows/upgrade-dependencies.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/upgrade-dependencies.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/upgrade-dependencies.ts
The `download-artifact` action should not use `path`.
---
> fix(deps): deps workflow fails due to patchfile going into the wrong directory

- src/__tests__/release/bump.test.ts
Fixes a test that was flaky based on when it was getting run (see #856).
---
> fix: flaky test

- CONTRIBUTING.md
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/util.ts
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/__tests__/web/nextjs-project.test.ts
- src/__tests__/web/nextjs-ts-project.test.ts
- src/__tests__/web/react-project.test.ts
- src/__tests__/web/react-ts-project.test.ts
- src/node-package.ts
- src/node-project.ts
By default, do not pin projen to the CLI version and let the dependency manager maintain the version. This also has the affect of enabling normal use of `yarn link`.
Update CONTRIBUTING to describe the local test workflow.
Fixes #151
---
> fix: "yarn link projen" is broken

- API.md
- src/github/mergify.ts
According to Mergify documentation [here](https://docs.mergify.io/conditions/#conditions), Projen interface is missing the conditional operators so that the configuration can be simplified. 
---
> feat: add conditional operators for mergify rule

- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/util.ts
- src/cli/cmds/new.ts
- src/cli/index.ts
- src/cli/macros.ts
- src/release/bump-version.ts
- src/util.ts
Also, enforce that `exec()` always pipes STDERR so that it is included in exception messages.
> feat(cli): do not show cli help on errors

- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/new.test.ts
This test doesn't seem to do what it claims since the --no-git flag isn't being passed in, and the description seems identical to the test immediately preceding it. It was probably added by accident.
---
> chore: remove duplicate unit test

- .github/workflows/release.yml
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/jsii.test.ts
- src/__tests__/release/__snapshots__/release.test.ts.snap
- src/release/publisher.ts
Since the publish job does not checkout the sources, we cannot really use projen tasks there. Instead, just emit the actual command and environment into the workflow. Not a huge deal.
---
> chore: do not use “projen publish:xxx” in publish jobs

- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/release/__snapshots__/release.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/release/release.ts
- src/typescript.ts
The `package` task for TypeScript deletes the `dist` directory before it runs. This conflicts with the release task that was introduced in #917 which emitted `version.txt` and `changelog.md` into `dist` for later consumption when the GitHub release is created.
To address this, we moved to cleanup of `dist` from the `package` to the `release` task.
---
> fix(release): typescript release is broken due to missing files

- src/version.ts
When using projen on a windows machine on a project with the version component, the workflows and tasks contained `\` in their path, thus resulting in a difference between windows/not-windows synths. It also breaks the release script when running in github actions.
This PR forces the use of posix slashes for those files.
---
> fix(release): use posix path for changelog and bump file

- src/typescript-typedoc.ts
I'm not sure that this was working for anyone else, but typedoc requires an entrypoint of some sort to be passed in. It also seemed reasonable to update the version of typedoc (the issue was present in both versions) so that it can support typescript 4.3.
As an opinioned change, I added the `disableSources` flag as well. Without that flag, typedoc generates links to the source in the html with a SHA that will be constantly changing. While a nice feature, it causes very noisy diffs.
---
> fix(docgen): add additional args to typedoc and update version

- src/__tests__/__snapshots__/new.test.ts.snap
- src/typescript/projenrc.ts
Fixes #948 
Uses the `--skip-project` flag on `ts-node` to "Skip reading `tsconfig.json`". 
---
> fix(jsii): `.projenrc.ts` accidentally relying on `tsconfig.json`

- src/__tests__/source-code.test.ts
- src/source-code.ts
If `code.line()` is called inside a block, it will create a line with trailing whitespace which would fail linters. Call `.trimEnd()` to trim.
---
> fix(source-code): empty lines have trailing whitespace

- API.md
- src/typescript-config.ts
Added new compiler options available in TypeScript 4.1 and 4.2
Specifically added flags for [noUncheckedIndexAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) and [noPropertyAccessFromIndexSignature](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature) to users to adopt these checks.
Default has been set to true as defaults seemed to align with "stricter" configuration generally.
---
> feat: expand TypeScrtiptConfigOptions

- src/inventory.ts
Small additional PR for module lookup with the following structure:
```
feat projen project -> common company projen project -> projen
```
The common company project can be installed in different places by npm/yarn based on external conditions. The previous code solved one situation but it is possible that the module is not found. This happens for instance when initiating a project within a monorepo with hoisting
With this change we rely on the node resolution system to find all nested projects.
---
> fix: Normal npm module lookup

- src/release/publisher.ts
---
Ran into issue when trying to manually set twine username and password secrets. Password secret was being set for both `TWINE_USERNAME` and `TWINE_PASSWORD`
Found typo in `release/publisher.ts` where password secret was being set for both environment variables.
After change can confirm that env vars are set correctly.
> fix(release): unable to set twine username secret

- .github/workflows/release.yml
- API.md
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/release/__snapshots__/release.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/github/task-workflow.ts
- src/release/publisher.ts
- src/release/release.ts
When new commits are pushed to the release branch, the release job will not upload the artifact but the publisher jobs will still execute (and fail, because there is no artifact).
This change adds a job condition that will only execute the publishing jobs if we are indeed releasing the latest commit. Otherwise, the publishers will be skipped and the workflow will not fail.
Fixes #723
---
> fix(release): publishing jobs fail when new commits are pushed

- .github/workflows/release.yml
- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/jsii.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/release/__snapshots__/release.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/release/publisher.ts
The github release publisher now needs to explicitly state which repo to work with because we do not check out the code.
---
> fix(release): github releases are broken due to missing --repo

- API.md
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/node-project.test.ts
- src/github/github.ts
- src/github/workflows.ts
You can now set `githubOptions.workflows` to `false` in order to just disable workflows without
completely disabling GitHub integration.
Resolves #828
---
> feat(github): allow disabling all workflows

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade.yml
- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/__snapshots__/new.test.ts.snap
- src/__tests__/integration/cdk8s/cdk8s.common.js
- src/__tests__/new.test.ts
- src/cli/cmds/new.ts
- yarn.lock
A recent change updated the minimum node version of projen itself to 14.x. This implies that it is now impossible to use it in environments with older node, including any existing workflows.
In the meantime, we set the min version back to 10.x.
NOTE: This change also relaxes engine checks during `projen new`. This technically means that users are able to create a new project within a non-compatible environment, but since engine checks are performed all the time anyway, they won't be able to go a long way without a compatible node version. The reason this was needed is because our "new" tests use the latest version of node when they test external projects and version 0.28.0 now requires node 14.x... Anyway - a bit of a mess.
--- …
> fix: projen incompatible with node 10.x

- API.md
- src/typescript-config.ts
Added missing props in `TypeScriptCompilerOptions` which are needed to re-map the imports.
---
> feat(tsconfig): expose "baseUrl" and "paths" in compilerOptions

- src/inventory.ts
by avoiding re-probing same dependencies multiple times
No new tests added as the functionality will still be the same.
It's just a performance boost when the extnernal module
has multiple dependencies (e.g. aws cdk v1).
Fixes #1101
---
> fix: speed up discovery of external types

- .projen/tasks.json
- src/__tests__/__snapshots__/integ.test.ts.snap
- src/__tests__/node-project.test.ts
- src/__tests__/upgrade-dependencies.test.ts
- src/__tests__/web/__snapshots__/nextjs-project.test.ts.snap
- src/__tests__/web/__snapshots__/nextjs-ts-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-project.test.ts.snap
- src/__tests__/web/__snapshots__/react-ts-project.test.ts.snap
- src/upgrade-dependencies.ts
When running the command separately on each dependency type (`dev`, `peer`, ...) everything is upgraded as expected.
So the solution proposed here is to expand the `npm-check-updates` command into 5 separate commands, each updating a different dependency type. 
Fixes https://github.com/projen/projen/issues/1110
---
> fix(upgrade): some dependencies are not upgraded when shared between different dependency types

- src/__tests__/release/__snapshots__/release.test.ts.snap
- src/release/bump-version.task.ts
- src/release/release.ts
I think PREFIX is clashing with an existing environment
variable used by nodejs or maybe nvm. When I run `yarn bump`
locally using manual releases and no prefix, PREFIX gets set
to `/usr/local`. Given the significance of that path I assume
that PREFIX is being used by some other tool on my system.
Making PREFIX naming more specific to avoid this problem.
---
> fix(release): prefix env variable clash

- src/__tests__/release/update-changelog.test.ts
- src/release/update-changelog.ts
Now that we're pulling from the release tag file
we have to strip the preceding `v` since the version
is recorded without it in changelogs.
Parsing rules might need to change depending on #1118, but as is it should unblock folks not using prefixes.
---
> fix(release): fix changelog release tag parsing

- src/__tests__/release/update-changelog.test.ts
- src/release/publisher.ts
- src/release/update-changelog.task.ts
- src/release/update-changelog.ts
Prefixes aren't recorded in the release changelog so
switching back to pulling the release version from
version.txt to simplify having to parse out the
major, minor, and patch version from the full release
tag.
---
> fix(release): update-changelog pull from version file

- .eslintrc.json
- API.md
- src/eslint.ts
- test/__snapshots__/eslint.test.ts.snap
- test/__snapshots__/integ.test.ts.snap
- test/eslint.test.ts
Without this setting, the eslint-import-resolver-typescript will not try to
resolve imports on the `@types/*` packages, leading to errors like the following
at build:
```
error  Unable to resolve path to module 'aws-lambda'  import/no-unresolved
```
By adding `{ alwaysTypeTypes: true }` to the typescript import resolver config,
the error is resolved.
---
> feat: support alwaysTryTypes config for typescript eslint import resolver

- src/awscdk/lambda-function.ts
Reverts projen/projen#1235. It appears this does not actually fix the bug
> chore: Revert "fix: lambdas are now produced with posix paths only"

- README.md
Changing the path from an absolute path to a relative path should make it appear correctly on Construct Hub
---
> fix: README logo url

- src/awscdk-app-ts.ts
- test/awscdk-app.test.ts
fixes #1205 
Setting context to undefined when CDK major version is >=2 
Only question: should it be undefined or an empty object?
---
> fix(awscdk-app-ts): unsetting context when cdk version > 2

- API.md
- src/javascript/bundler.ts
The current docstring describes a parameter that does not exist on the method
---
> chore: fix addBundle docstring

- API.md
- src/release/publisher.ts
- src/release/release-trigger.ts
- test/release/release-trigger.test.ts
This adds the ability for a user to customise (or disable) the git-push command which is run as part of a manual release.
closes #1267 
---
> feat: allow customising or disabling git-push used by manual release

- src/awscdk/awscdk-app-ts.ts
According to the `AwsCdkTypeScriptAppOptions` `srcdir` and `testdir` are configurable but they weren't.
This would fix it.
---
> fix(awscdk-app-ts): srcdir and testdir are not configurable

- src/javascript/node-package.ts
Super minor, but I noticed it the other day and it seems worth fixing in case someone gets confused.
Luckily, `addBundledDeps` was already correct.
---
> chore: `bundledDeps` docstring incorrectly mentions `peerDependencies`

- .mergify.yml
- src/github/auto-merge.ts
- test/__snapshots__/integ.test.ts.snap
- test/github/__snapshots__/mergify.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
The `commit_message` option is deprecated and replaced by
`commit_message_template`.
---
> chore: stop using mergify's commit_message

- .projen/deps.json
- package.json
- src/typescript/typescript.ts
- test/__snapshots__/integ.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
- yarn.lock
`@types/node` versions numbers match the node runtime versions'
`major.minor`, however new releases are only created when API changes
are included in a node release... We might for example have dependencies
that require `node >= 12.22`, but as 12.21 and 12.22 did not include API
changes, `@types/node@12.20.x` is the "correct" version to use. As it is
not possible to easily determine the correct version to use, we pick up
the latest version.
BREAKING CHANGE: the default version of `@types/node` installed if no
`minNodeVersion` is specified on Node projects is now `^12` instead of
`^14`.
---
> chore: use major-pinned version of @types/node

- API.md
- src/awscdk/auto-discover.ts
- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
- test/awscdk/integration-test.test.ts
Changes CDK v2 integration tests so that they don't use the v1 feature flags.
Fixes #1343
---
> fix: CDK v2 integration tests should not use v1 feature flags

- .github/workflows/integ.yml
- .github/workflows/release.yml
- .projenrc.js
- API.md
- package.json
- src/cli/cmds/new.ts
- src/java/projenrc.ts
- src/javascript/projenrc.ts
- src/javascript/render-options.ts
- src/option-hints.ts
- src/project.ts
- src/projects.ts
- src/projenrc-json.ts
- src/python/projenrc.ts
- src/run-projenrc-json.task.ts
- src/typescript/projenrc.ts
- test/java/java-project.test.ts
- test/java/projenrc.test.ts
- test/json/projenrc.test.ts
- test/projects.test.ts
- test/python/projenrc.test.ts
Fixes #1344
In order to publish to Go, we have to rename `NewProject`, since any type named `NewXxx` can potentially conflict with Go constructor functions with the name `NewXxx` generated by jsii.
BREAKING CHANGE: `NewProject` has been renamed `InitProject`, and `NewProjectOptionHints` has been renamed `InitProjectOptionHints`
---
> feat: projen library in go

- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
This makes it impossible to work with `App`s containing assets since the
paths are different in the GitHub Action.
Use the same CLI switches as the ones used in in
`@aws-cdk/cdk-integ-tools`.
https://github.com/aws/aws-cdk/blob/fd149b1e6557337b01d2232e2ba0fd410ba903dd/tools/%40aws-cdk/cdk-integ-tools/lib/integ-helpers.ts#L190-L192
---
> fix: CDK integration snapshots have local paths when working with assets

- .mergify.yml
- .projen/tasks.json
- .projenrc.js
- docs/publisher.md
- test/release/release.test.ts
To disable publishing, set `publishDryRun` to `true` in your project definition.
The feature was actually added in #1359 - this commit just adds a test and docs.
Also: fixes the integ test.
---
> feat(release): dry-run

- .github/workflows/build.yml
- .github/workflows/release.yml
- .projen/tasks.json
- API.md
- src/cdk/jsii-project.ts
- src/javascript/node-project.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
Adds a property to `NodeProject` which can be used to determine where the npm tarball is so that release jobs can use it instead of assuming things.
Fixes #1376
---
> fix(node): npm releases are broken for non-jsii projects

- API.md
- src/javascript/node-package.ts
- test/__snapshots__/inventory.test.ts.snap
- test/javascript/__snapshots__/node-package.test.ts.snap
- test/javascript/node-package.test.ts
Adds support for node package manifest `bugs` field via `issueTrackerOptions` in
`src/javascript/node-package.ts::NodePackageOptions`
Resolves #1369
---
> feat(node): package manifest "bugs" field

- .github/workflows/release.yml
- src/build/build-workflow.ts
- src/github/constants.ts
- src/release/publisher.ts
- src/release/release.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
Same as https://github.com/projen/projen/pull/1384, but for the release workflow. 
Should free the release which is currently [failing](https://github.com/projen/projen/runs/4644112485?check_suite_focus=true):
```console
Run npx projen package:js
npx: installed 65 in 5.454s
Unknown command: package:js
Error: Process completed with exit code 1.
```
---
> chore: pwd artifact for release

- .github/workflows/release.yml
- .projenrc.js
Following https://github.com/projen/projen/pull/1408, I downloaded the build artifact and observed `package.json` indeed contains the correct future version:
```json
...
"version": "0.46.9",
...
```
In addition, the publishing jobs successfully packaged all artifacts, the only way they could do that is by using this build artifact because the normal repository isn't available for them. 
This makes me confident enough the release should go through well. 
---
> chore: enable release

- .github/workflows/build.yml
- .github/workflows/upgrade-main.yml
- .projen/tasks.json
- src/build/build-workflow.ts
- src/cdk/consts.ts
- src/cdk/jsii-project.ts
- src/github/workflow-actions.ts
- src/release/release.ts
Now that the upgrade workflow can trigger a proper build when the pull request is created, we no longer need to run pacmak.
Additionally, add "--staged" when doing `git diff` for tamper-checks as a follow up on https://github.com/projen/projen/pull/1383#discussion_r776334094
---
> fix(jsii): upgrade workflow no longer needs to run pacmak

- .github/workflows/build.yml
- src/build/build-workflow.ts
- src/github/workflow-actions.ts
- test/__snapshots__/integ.test.ts.snap
- test/__snapshots__/node-project.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Fixes #1423 and fixes #1422 by failing the build job when a mutation was found and allowing the `self-mutation` and the `anti-tamper` jobs to execute even if the `build` job failed.
Here is an [example](https://github.com/projen/projen/runs/4664625019).
---
> fix(build): build should fail if mutations were found

- .github/workflows/build.yml
- src/build/build-workflow.ts
- src/github/workflow-actions.ts
- test/__snapshots__/integ.test.ts.snap
- test/__snapshots__/node-project.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Improve the error displayed when mutation is found during build, to indicate to forks that they need to update their branch.
---
> chore: improve mutation error message

- .github/workflows/release.yml
- API.md
- src/cdk/jsii-project.ts
- src/release/publisher.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
Introduce a way to configure github pre-publishing steps so that jsii projects can properly prepare the working directory for the expected paths of the release job.
Fixes https://github.com/projen/projen/issues/1431
---
> fix(jsii): github release not created

- API.md
- src/build/build-workflow.ts
- src/javascript/node-project.ts
- test/node-project.test.ts
Fixes https://github.com/projen/projen/issues/1491
Allow using a different github runner than `ubuntu-latest` when running the build in github action.
---
> feat: allow build workflow github runner to be customised

- test/__snapshots__/node-project.test.ts.snap
- test/node-project.test.ts
`mutableBuild` is enabled by default, so we should have at least one test validating that disabling it does the right thing.
---
> chore: update mutableBuild unit tests

- src/cleanup.ts
- src/file.ts
- src/project.ts
- test/__snapshots__/cleanup.test.ts.snap
- test/cleanup.test.ts
To avoid unnecessary thrashing of projen managed files, we can skip cleaning up files that we know we're just going to be creating again during synthesis. This means that changed files will simply be overwritten during synthesis. Even better, unchanged files won't be written at all.
With this PR, an orphaned file is one that is present in `files.json` (from the previous synthesis) but not one of the files that are about to be synthesized.
Included some refactoring in `cleanup.ts` to make the control flow more (hopefully) clear with this additional logic.
fixes #1484 
---
> fix(cleanup): Only clean up orphaned files

- .projen/tasks.json
- .projenrc.js
This fixes a feedback loop where contributors add some change to projen (that happens to affect projen's own configuration files), and running `build` will compile and run all tests but not necessarily run update projen's own config because the `compile` task runs after `default`.
This is not totally fool-proof, since it's possible the change to projen could affect the actual build steps and thus require a full build again, but it might be possible to make this smarter in the future with https://github.com/projen/projen/issues/1515.
---
> chore: resynth after compiling projen

- API.md
- src/awscdk/auto-discover.ts
- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
- test/awscdk/integration-test.test.ts
Allows users to add AWS CDK integration tests consisting of stages with multiple stacks.
```ts
new awscdk.IntegrationTest(project, {
name: "my-stage",
entrypoint: "test/my-stage.myinteg.ts",
stacks: ["my-stage/*"],
tsconfigPath: project.tsconfigDev.fileName,
cdkDeps: project.cdkDeps,
});
```
Fixes #1495
---
> feat(awscdk): allow users to integration test multi-stack stages

- API.md
- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
Per discussion in https://github.com/projen/projen/pull/1496#discussion_r783660269, `**` is a better choice for the default integration test stack to deploy, as using `**` targets stacks including those nested in stages.
---
> fix(awscdk): integration tests should deploy ** by default instead of *

- src/cdk8s/cdk8s-app-ts.ts
- test/cdk8s-app-project-ts.test.ts
Changes the default `cdk8s import` location to `./src/imports` so that imported resource specs can be accessed from the rest of the cdk8s app.
Fixes #1534
BREAKING CHANGE: The `import` task in the `Cdk8sTypeScriptApp` project now outputs to the `src` directory by default instead of the project root.
---
> fix(cdk8s): import location should be in the rootDir

- API.md
- src/cdk8s/cdk8s-app-ts.ts
- test/__snapshots__/inventory.test.ts.snap
- test/cdk8s-app-project-ts.test.ts
Adds `cdk8sImports` which allows the user to import additional Kubernetes specs.
Fixes #1535
﻿---
> feat(cdk8s): import additional specs

- src/awscdk/integration-test.ts
- test/awscdk/integration-test.test.ts
Currently when using a `AwsCdkConstructLibrary` it must be manually
added to the project.
---
> feat: install AWS CDK CLI for integration snapshot tests

- src/javascript/node-project.ts
- test/node-project.test.ts
If `github: false` is configured the `NodeProject` throwing an error, when there is auto approval configured.
The error occured with an external projen project type, which has presets for github, but should just be disabled on some projects. I would like to keep the configuration and just disable the github feature.
---
> fix: disabled github components throws error

- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
- test/awscdk/integration-test.test.ts
The task is named `integ:snapshot-all` and can be used together with the
feat added in #1476.
---
> feat(awscdk): task to update snapshot of all integrations tests

- .projen/tasks.json
- .projenrc.js
Also removed unused imports in .projenrc.js.
Not sure if there's another way to resolve the linked issue, but I think not having publish a new version every day would be nice.
If it would be better to disable markmac from auto updating projen instead then this PR can be closed.
fixes #1553 
---
> fix: Remove markmac from autodependency updates

- API.md
- src/cdk8s/cdk8s-app-ts.ts
- test/__snapshots__/inventory.test.ts.snap
- test/cdk8s-app-project-ts.test.ts
Allows users to specify the `k8s` version to import.
Fixes #1557 
---
> feat(cdk8s): import an explicit k8s spec version

- API.md
- src/build/build-workflow.ts
- src/javascript/node-project.ts
- test/__snapshots__/inventory.test.ts.snap
- test/node-project.test.ts
This PR is about allowing the build workflow trigger to be customised. Currently it defaults to `pull_request` and `workflow_dispatch` triggers and I would like to modify it with something else if possible.
---
> feat: customise build workflow trigger in NodeProject

- src/github/workflows-model.ts
Adding this feature to allow setting the JobMetrix values to other primitive data types rather than string. For instance, I want to set the session length for AWS assume role github action which is a number. This is comming as a value from matrix.
---
> feat(github): allow JobMatrix to accept values other than string

- src/release/bump-version.task.ts
- src/release/bump-version.ts
- test/release/bump.test.ts
> fix: release task bumps to wrong version when majorVersion is 0

- docs/api/API.md
- src/awscdk/lambda-function.ts
- test/awscdk/__snapshots__/lambda-function.test.ts.snap
- test/awscdk/lambda-function.test.ts
The default Node.js HTTP/HTTPS agent creates a new TCP connection for
every new request. To avoid the cost of establishing a new connection,
configure the SDK for JavaScript to reuse TCP connections.
Also add an opt-out.
Taken from the `NodejsFunction`.
See https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
---
> feat(awscdk): AWS SDK connection reuse for Lambda functions

- docs/api/API.md
- src/javascript/upgrade-dependencies.ts
- test/upgrade-dependencies.test.ts
Small change that moves the `createTask` step of `UpgradeDependencies` into the constructor, so that it is added during project instantiation. This allows the task to be overwritten with `project.removeTask()` per the error message:
```
Error: A task with the name upgrade already exists. To override it, call removeTask first and then create the new task.
```
This previously did not work, as the error was actually being thrown by the `UpgradeDependencies.createTask()` function during the pre-synth step. I considered instead adding error handling during this step, but could not decide whether silently not creating a task if one already existed or throwing an error with a clearer message would be a better behaviour, and decided on this approach instead.
Also includes a couple of non-breaking …
> fix(upgrade-dependencies): upgrade task cannot be overwritten

- docs/api/API.md
- src/awscdk/auto-discover.ts
- src/awscdk/integration-test.ts
- test/awscdk/__snapshots__/integration-test.test.ts.snap
- test/awscdk/integration-test.test.ts
Adds a `pathMetadata` option to IntegrationTest and the integration test options to auto-discover classes so that users can enable path metadata for their integration tests.
---
> feat(awscdk): allow integration test path metadata

- src/github/workflows-model.ts
Add missing job permissions.
The available scopes are listed here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
---
> feat(github): add new job permissions

- src/web/react.ts
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Using `yarn eslint` I noticed a rule break defined here https://github.com/projen/projen/blob/main/.eslintrc.json#L95
https://typescript-eslint.io/rules/no-floating-promises/
```
Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator.eslint[@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises)
```
---
> fix: no-floating-promises

- .projen/deps.json
- .projen/tasks.json
- package.json
- src/cdk/jsii-project.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- yarn.lock
Sometimes while doing a local build, I encounter the build hanging because the relevant version of jsii-pacmak hasn't been installed:
```
👾 package-all » package:js | npx jsii-pacmak@$jsii_version -v --target js
Need to install the following packages:
jsii-pacmak
Ok to proceed? (y)
```
Instead let's just add it as a dev dependency outright.
---
> fix: jsii-pacmak is not included as dev dependency

- docs/python.md
When the documentation was created it was not possible
to write the project setting in python file. Now, no
longer is necessary to use .projenrc.js as .projenrc.py
is available.
---
> fix: python documentation refers to `projenrc.js` instead of `.projenrc.py`

- .projen/deps.json
- .projenrc.js
- package.json
- test/__snapshots__/new.test.ts.snap
- test/new.test.ts
- yarn.lock
Currently new projen development builds are failing (example: https://github.com/projen/projen/pull/1721) because `yaml` published v2.0.0 to the `next` tag, in which they bumped the minimum node version they require from 12 to 14. Since new development builds are automatically picking this up and projen still supports node v12, this PR pins the version of `yaml` so the new version isn't picked up by `yarn install`.
This should fix #1740
We should also upgrade the minimum node version projen supports, but it's better to do that in a separate PR. (Issue: https://github.com/projen/projen/issues/1739)
---
> fix: creating new project with node v12 fails

- src/release/update-changelog.ts
- test/release/update-changelog.test.ts
The first ever changelog entry created by standard-version
doesn't link to a diff because none exists yet. For that
reason there are no markdown link brackets around the
version, which was causing the first manual release to
fail.
Closes #1749
---
> feat(publisher): match first changelog entry

- docs/api/API.md
- src/github/workflows-model.ts
This doesn't change the API, but moves generic `Step` properties out of `JobStep`. This is necessary because the [syntax](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) for Action Metadata steps is ever so slightly different than a job step.
---
> chore: pull out generic `Step` from `JobStep`

- docs/node.md
- src/cli/index.ts
- src/util.ts
Node v12 reaches end of life on April 30, 2022. This PR adds a warning that projen will be dropping support for old node releases.
We'll give this message a week to incubate before actually bumping the version we support (#1768).
---
> chore: deprecate node v12 support

- src/javascript/node-package.ts
- src/javascript/util.ts
- test/javascript/node-project.test.ts
Added validation to include trailing slash in the `registryUrl`
Fixed `ca:login` task by:
- Removed `repository` parameter from aws call
- Removed https:// from registryUrl used in npm config
---
> fix(node-project): code artifact login command

- .projen/deps.json
- package.json
- src/typescript/typescript.ts
- test/__snapshots__/integ.test.ts.snap
- yarn.lock
Pins the version of `ts-jest` to `^27`, to fix an issue with auto-approve PRs having `jest` at 27 but `ts-jest` at 26, which causes build failures. 
Fixes #1813 
---
> fix: Pin the version of ts-jest to 27

- docs/api/API.md
- src/python/python-project.ts
- test/__snapshots__/inventory.test.ts.snap
- test/new.test.ts
- test/python/python-project.test.ts
Fixes #1807
To manage a PythonProject with a JavaScript projenrc file, the project will need to have these options configured:
```js
projenrcJs: true,
```
Or pass the option in the command line when creating the project, e.g. `npx projen new python --projenrc-js`.
---
> fix: cannot create `PythonProject` with `.projenrc.js`

- docs/api/API.md
- docs/escape-hatches.md
- src/project.ts
- test/project.test.ts
Adds an escape hatch method to all projects that allows removing files.
In the future, if projen uses the `constructs` programing model, this probably won't be needed since constructs have their own `node.tryRemoveChild` method - but for now this should be able to substitute for most use cases.
---
> feat: `tryRemoveFile` escape hatch

- docs/awscdk.md
> fix: replace deprecated reference to cdk-triggers

- docs/api/API.md
- src/javascript/eslint.ts
- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
fixes #1831 
BREAKING CHANGE: EslintOptions.lintProjenRc is now a string
---
> fix(typescript): eslint task lints projenrcts

- .projen/deps.json
- .projen/tasks.json
- .projenrc.js
- package.json
- yarn.lock
The new version of yaml (2.1.0) uses some types that are not supported in TypeScript 3.9, so projen fails to compile if we upgrade to it. Pin to the existing version for now.
---
> chore: pin yaml in projen

- docs/api/API.md
- src/javascript/eslint.ts
- test/javascript/eslint.test.ts
Adds a configuration option to the ESLint module to support writing the
configuration file as yml instead of json. Still writes as json by
default. ESLint natively supports yml configuration files and they're
nicer to work with. See
https://eslint.org/docs/user-guide/configuring/configuration-files
---
> feat(eslint): support eslint config in yaml form

- src/typescript/typescript-typedoc.ts
> fix(typedoc): updated typedoc dependency when using doc generation in typescript projects

- docs/api/API.md
- src/build/build-workflow.ts
Since all of the options are optional, we can provide a default value so that passing an options object is not required.
---
> fix: addPostBuildJobTask options are required

- src/javascript/node-project.ts
When switching on `releaseToNpm` I got a confusing error message
saying I wasn't allowed to. The error message did not match the
actual reason.
---
> chore: fix confusing error messages

- src/typescript/projenrc.ts
TypeScript projects using `projenrcTs` specify `typescript` and `ts-node@^9` as dev dependencies by default. The misalignment between the two makes `ts-node` fail to execute `synth`.
This PR simply removes the semver notation from `ts-node`, so new projects are created specifying the latest stable (and supposedly compatible) release of both as dev dependencies.
Fixes: #1880 
---
> fix(typescript): aligns typescript and ts-node default versions

- src/awscdk/awscdk-app-ts.ts
- src/cdk8s/cdk8s-app-ts.ts
Addition to #1881
#1880 is still present in `awscdk-app-ts` and `cdk8s-app-ts` apps
---
> fix(awscdk-app-ts,cdk8s-app-ts): use ts-node default versions

- docs/api/API.md
- src/awscdk/awscdk-deps.ts
- src/logger.ts
- test/awscdk/awscdk-construct.test.ts
Proactively help users avoid errors by logging a warning if a CDK v1 dep has been added to the projenrc file of a CDK v2 project.
projen doesn't have a notion of "Annotations" like AWS CDK, so for now this warning is logged during the preSynthesize hook, at which point most dependencies should have been to the project's `Dependencies`.
---
> feat: warn users if CDK v1 deps are installed in a CDK v2 project

- .projen/tasks.json
- src/cdk/jsii-project.ts
- test/__snapshots__/integ.test.ts.snap
Currently, the `package` task for jsii projects running in CI environments does the following:
```console
rsync -a . dist --exclude .git --exclude node_modules
```
It does this to prepare the `dist` directory for subsequent `package:${lang}` in the GitHub workflow. (More details [here](https://github.com/projen/projen/pull/1631))
The problem is that when this command is executed, the `dist` directory is not empty, it contains:
- `releasetag.txt`
- `version.txt`
- `changelog.md`
These are created in the `bump` task. This in turn creates a weird structure after the `rsync` is executed:
```console
dist/
├─ releasetag.txt // duplicated and misplaced
├─ version.txt // duplicated and misplaced
├─ changelog.md // duplicated and misplaced
├─ package.json
├─ lib/
├─ dist/
│  ├─ releasetag.txt
│ …
```
> chore: remove bump files from npm tarball

- docs/api/API.md
- src/awscdk/lambda-extension.ts
- src/awscdk/lambda-function.ts
- test/awscdk/__snapshots__/lambda-extension.test.ts.snap
Added NodeJS Lambda Runtime 16.x to be able to use them for [AWS Lambda Functions](https://projen.io/awscdk.html#aws-lambda-functions) (its possible to use them since [aws-cdk v2.24.0](https://github.com/aws/aws-cdk/releases/tag/v2.24.0), [blogpost](https://aws.amazon.com/de/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/).
Tested the changes in my local project.
I've tried to keep as less changes as possible. 
Let me know if something is off and should be fixed
---
> feat(awscdk): add lambda runtime nodejs16.x

- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
Closes #1903 
The change in #1832 inadvertently removed required configuration for files on `projenrc` to be linted. This change restores that config by once again creating the `ProjenrcTs` component _after_  the `Eslint` component. It also adds `projenrc` as a `testDir`, so files will be linted by the eslint task.
This PR is aiming to resolve #1903 with minimal changes. I felt that the current implementation of the `Eslint` component is mixing responsibilities a bit (is it aware of projen, how much is it aware?) and makes some assumptions about what it thinks it knows about projen. **tl;dr I didn't really want to get into it.** But please let me know if you do want me to!
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix: restore ability to lint files in projenrc src directory

- README.md
We need to run `npx projen new <type>` instead of `npx projen <type>` to initialize a project.
Sorry, I'm not sure what is an appropriate title for this PR so it would be great if you could fix it. 🙏 
---
> chore: projen new command in README.md

- src/release/publisher.ts
Adding a condition to the git publish command, which performs
the same check as the bump command. If the last commit was a release
commit, it doesn't make sense to try to publish again. Doing so
actually causes an error because bump is skipped which means there
is no version file to read.
---
> fix(publisher): add manual publish condition

- .projen/deps.json
- .projen/tasks.json
- src/cdk/jsii-project.ts
- test/__snapshots__/integ.test.ts.snap
Fixes #1964
I tested the changes by creating a new awscdk-construct project in a new directory following the instructions here: https://github.com/projen/projen/blob/main/CONTRIBUTING.md#testing-against-local-projects
---
> fix(awscdk-construct): new project fails to build

- .projen/deps.json
- package.json
- src/javascript/upgrade-dependencies.ts
- test/__snapshots__/integ.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
- yarn.lock
due to security vulnerabilities
See https://github.com/raineorshine/npm-check-updates/issues/1145
Fixes https://github.com/projen/projen/issues/1963
---
> fix(dev-deps): upgrade npm-check-updates to 15.3.3

- docs/api/API.md
- src/awscdk/lambda-extension.ts
- src/awscdk/lambda-function.ts
- test/awscdk/__snapshots__/lambda-extension.test.ts.snap
- test/awscdk/__snapshots__/lambda-function.test.ts.snap
- test/awscdk/lambda-extension.test.ts
- test/awscdk/lambda-function.test.ts
Allow to use custom Lambda runtimes for bundled functions.
Remove the "coupling" with the enum from `aws-cdk-lib.aws_lambda`
so the runtime can be updated to a newer runtime without having to
update the minimum version of the AWS CDK to depend on.
---
> feat(awscdk): custom Lambda runtimes

- src/awscdk/awscdk-pytest-sample.ts
The python app file being generated by awscdk-app-py is main.py but the test_example.py is trying to import from my_stack, causing the first build to fail. 
---
> fix(awscdk): fix pytest import path

- docs/api/API.md
- docs/releases.md
- src/release/bump-version.task.ts
- src/release/bump-version.ts
- src/release/release.ts
- test/__snapshots__/inventory.test.ts.snap
- test/release/bump.test.ts
This new option is really convenient when you have a generated project that is self updating like the cdktf pre-built providers. With the current setup it's impossible to increase the major version without manual intervention. Since breaking changes in a 0.x version only result in a minor version increase there is no way to get to a higher major version.
---
> feat(release): add option to set the minimal major version

- .gitattributes
- src/cdk/jsii-docgen.ts
- test/__snapshots__/integ.test.ts.snap
The API.md file generated by jsii-docgen is machine-generated, so it should be annotated as such in PR diffs.
---
> fix(jsii-docgen): annotate output as generated

- test/release/bump.test.ts
- test/release/tag.test.ts
- test/util.ts
When running locally, one might have `tag.gpgsign` configured which causes these tests to hang on an open editor/expecting user input. This change disables tag signing as we already do for commits
---
> chore: fix tests failing locally if git gpgsign is configured

- docs/api/API.md
- src/vscode/index.ts
- src/vscode/settings.ts
- src/vscode/vscode.ts
- test/vscode/settings.test.ts
Settings keys languages are not further typed as there are A LOT of
them and plugins can add any new values to it.
Setting values are not typed as they are essentially of type JSON which is
difficult to express in TS and a jsii compatible way.
---
> feat(vscode): support VS Code workspace settings

- docs/releases.md
I struggled in the beginning understanding how I could "catch up" a project that was taking on projen to get version numbers to match up, so I added a section about it.
---
> feat: Adding notes about forcing release versions

- docs/api/API.md
- src/java/pom.ts
- test/java/__snapshots__/pom.test.ts.snap
- test/java/pom.test.ts
I'd like to be able to build a lambda deployment package using a `JavaProject`. For this I need to use the `maven-shade-plugin` as mentioned here: https://docs.aws.amazon.com/lambda/latest/dg/java-package.html
The plugin execution needs `<phase>package</phase>` in order to run as part of the build. This PR allows this to be optionally specified.
See also: https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag
---
> feat(pom): support adding phase to plugin execution

- src/web/next.ts
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
Updates `minNodeVersion` according to current Next.js requirements
Changes `workflowNodeVersion` to use the oldest version still supported by Node.js
---
> fix(nextjs): default node versions for Next.js are out-of-date

- src/release/bump-version.ts
- test/release/bump.test.ts
This change fixes the behavior of the bump task when a prerelease suffix is set, there are not yet any prerelease tags, but there are other normal tags for the current major version. The current behavior results in "first release" behavior. What should happen, and what this change implements, is a correct semver increment into a new prerelease.
For example,
Given
- A major version of `1`
- a previous tag of `1.2.0`
- a new `feat` commit
- a `prerelease` setting of `beta`
Previously a bump would have resulted in `1.0.0-beta.0`.
Now a bump will result in `1.3.0-beta.0`, as expected.
---
> fix(release)!: existing tags for prerelease not respected

- docs/api/API.md
- src/awscdk/index.ts
The `AwsCdkDepsPy` class cannot be discovered by an external project as it's not exported in the module's `index.py`. I was able to confirm this in my external project by modifying the locally-installed `projen`: by updating `lib/awscdk/index.d.ts` and `lib/awscdk/index.js` to export the module, my project was able to find `AwsCdkDepsPy` and build. Removing those added exports made it unable to find it again.
---
> fix(awscdk): Export `awscdk-deps-py` in index

- src/web/react.ts
- test/web/__snapshots__/react-ts-project.test.ts.snap
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62300
---
> fix(react-ts): `@types/express` (4.17.14) and `@types/express-serve-static-core` (4.17.31) break compilation

- src/github/github-credentials.ts
Fixes an error in the docs for GithubCredentials so it shows the right secret name for `PROJEN_APP_ID`.
Fixes #2147
---
> fix(github): correct secret name for GithubCredentials docs

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- docs/api/API.md
- src/build/build-workflow.ts
- src/github/task-workflow.ts
- src/github/workflow-actions.ts
- src/javascript/node-project.ts
- src/release/publisher.ts
- src/release/release.ts
- test/__snapshots__/integ.test.ts.snap
- test/__snapshots__/inventory.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/task-workflow.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/javascript/node-project.test.ts
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Fixes: #2194
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows
BREAKING CHANGE: Requires self-hosted GitHub Actions runners to be updated to version 2.297.0 or greater.
---
> fix(github)!: set-output warning from main-upgrade workflow

- .github/workflows/build.yml
- .github/workflows/release.yml
- src/github/workflows.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
BREAKING CHANGE: If you have customized the `package-python` or `package-dotnet` jobs of the release workflow, please review the changes for the release of the respective action.
actions/setup-python@v4: https://github.com/actions/setup-python/releases/tag/v4.0.0
actions/setup-dotnet@v3: https://github.com/actions/setup-dotnet/releases/tag/v3.0.0
---
> chore(github)!: upgrade versions of workflow actions to `setup-python` and `setup-dotnet`

- .projen/tasks.json
- src/javascript/jest.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/cdk8s/__snapshots__/integration-test.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
This argument does not exist and hasn't existed since at least 22.x:
https://jestjs.io/docs/cli
https://archive.jestjs.io/docs/en/22.x/cli
This argument was added in Dec 2020 by a larger commit adding build tasks: 95112272c2b192144293c1064c77b2d8da354b8f
And before that, the whole file did not exist and the project has no mention of `--all`. So I cannot deduce the original reason for adding this argument.
---
> fix(javascript): jest cli doesn't have an`--all` argument

- src/awscdk/cdk-tasks.ts
Allow user to pass arguments to CDK deploy and destroy tasks — e.g. stack name 
or `--all` are commonly used.
`projen deploy my-stack` 🎉 
---
> feat(cdk): allow user to pass arguments to deploy and destroy tasks

- docs/github.md
There's a minor issue with the module imports in the example presented on the GitHub component documentation page; this PR aims to correct the issue.
---
> chore(docs): fix imports in GitHub example

- docs/api/API.md
- docs/programmatic-api.md
- src/projects.ts
Caused me needless pain when trying to use `CreateProject` API.
Excerpt from my local projen .jsii file.
---
> chore: fix wrong documentation for projectfqn

- src/awscdk/awscdk-deps.ts
The CDK team [recently](https://github.com/aws/aws-cdk/issues/21268#issuecomment-1267065439) started publishing the `integ-runner` package under both V1 and V2, so adding it here to eliminate inaccurate WARNING log messages during project synthesis.
---
> chore(awscdk): add integ-runner to CDK v1/v2 packages list

- docs/api/API.md
- src/cdk/jsii-project.ts
- src/javascript/node-project.ts
- test/cdk/jsii.test.ts
Fix #1799 #1006
Allow workflow setup steps to be used by extensions of node-project. 
This change will enable for example a step that sets NPM authentication for private repos before build and publish.
---
> fix(jsii): run workflow setup steps for language jobs

- .github/workflows/upgrade-main.yml
- src/javascript/upgrade-dependencies.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
The second step of this workflow that handles opening the pull request
is unnecessarily broad. Because the `PROJEN_GITHUB_TOKEN` (or the
otherwise configured token) will have `contents:write` and
`pull-requests:write` and that token is the one that is used to actually
push the content and open the pull request (as part of the
`peter-evens/create-pull-request` action), the `GITHUB_TOKEN` can be
used exclusively to checkout the branch with `contents:read`.
This change reduces the permissions of the `GITHUB_TOKEN` to the minimal
amount required and also reduces the places the configured token is used
to creating the pull request.
---
> chore(javascript): reduce the scope of the upgrade dependencies token

- src/cdk/auto-discover-base.ts
Fixes #2344
Autodiscovered lambdas use back-slashes in their entrypoints when generated on Windows. This causes the generated github workflows to fail. Forcing posix path format for entrypoints fixes the workflows while still being compatible with esbuild on Windows.
---
> fix: use posix paths for autodiscovered lambda entrypoints

- src/awscdk/lambda-function.ts
> fix: use posix paths for generated lambda construct files

- docs/api/API.md
- src/projects.ts
Currently it's not really possible for external project types to distinguish between when a project is being created versus routine synth's. 
Being aware of this can be useful for certain types of project customizations, especially given external projects' limited ability to customize the "projen new ..." experience. 
This PR sets an environment variable (`PROJEN_CREATE_PROJECT=true`) in the VM used to create the project, thus allowing external project types to be aware of the nature of the current synthesis.
---
> chore(projects): Set environment variable in VM when creating new project

- docs/api/API.md
- src/python/python-project.ts
- test/__snapshots__/inventory.test.ts.snap
- test/python/poetry.test.ts
Explicitly unsets pip, setuptools, and venv if poetry is set to true. This enables the creation of a PythonProject with the `--poetry true` flag.
Considered throwing errors if both poetry and pip were set to true, but opted instead to provide warnings in the interface instead. If there is a use case for poetry being set with one or more of pip, setuptools, and venv, we can re-evaluate this.
fixes #1863
---
> fix(python): creation of PythonProject with poetry

- docs/api/API.md
- src/javascript/jest.ts
Contrary to ESLint, Prettier, and most of the other components `Jest` is not extending the `Component` class but just a generic class that can only be accessed via `project.jest` property (if set)
This PR proposes converting the `Jest` class into the `Component` subclass for the following benefits:
* unification of approach with Eslint, Prettier, Projenrc, and other components
* providing `Jest.of(project)` API to be in line with Eslint and Prettier components and simplify accessing/extending Jest from outside components
* Facilitates future [migration to Constructs](https://github.com/projen/projen/pull/1671/files#diff-02bcf880af61bcbdba8cd4974d4a8ac84d32fcc0d4f4fb08d05cc053d3176c42) if that hopefully will happen one day
Additional small fixes in this PR:
* adding Jest external config to …
> feat(jest): convert Jest to Component

- docs/api/API.md
- src/docker-compose/docker-compose-network.ts
- src/docker-compose/docker-compose-render.ts
- src/docker-compose/docker-compose-service.ts
- src/docker-compose/docker-compose.ts
- src/docker-compose/index.ts
- test/docker-compose/docker-compose.test.ts
Closes #2397. I'm adding support for service networks. Just like volumes they can be assigned to multiple services. A top-level `networks` object holds the network configuration and services can reference them using it's name.
This makes it possible to generate docker-compose files like this:
```YAML
version: "3.7"
services:
busybox:
image: busybox
networks:
- traefik
networks:
traefik:
external: true
```
```typescript
import { DockerCompose } from 'projen';
const dockerCompose = new DockerCompose(project);
const service = dockerCompose.addService('busybox', {
image: 'busybox',
networks: [DockerCompose.network('traefik', { external: true })],
})
// or:
service.addNetwork(DockerCompose.network('traefik', { external: true }))
```
--- …
> feat(docker-compose): support defining networks

- docs/api/API.md
- src/javascript/typescript-config.ts
Allows to require use of the `override` keyword to indicate that a member overrides a declaration from a parent type, improving code readability and providing additional protection against typos and rename churn.
---
> feat(typescript): support `noImplicitOverride`

- docs/api/API.md
- src/cdk/jsii-project.ts
- src/javascript/node-package.ts
- src/javascript/node-project.ts
- test/__snapshots__/integ.test.ts.snap
- test/__snapshots__/inventory.test.ts.snap
There is currently an [issue](https://github.com/pnpm/pnpm/issues/5985) with PNPM in which ca:login fails to find the correct npm registry value for authentication in the latest version.
To mitigate this we want to be able to specify the version of PNPM to use in the Github workflow. 
This may help with future incompatibilities as well.
~This change also updates the configuration of **pnpm/action-setup** to use `latest` (currently 7.29.0) instead of being hard coded to 7~
Upon code review feedback this update now sets the default to version 7.   
---
> feat(node-package): Added ability to set pnpm version for action-setup

- src/task-runtime.ts
- src/task.ts
- src/tasks.ts
- test/__snapshots__/projects.test.ts.snap
- test/tasks/runtime.test.ts
Project types that do not use `.projenrc.ts` cannot guard against end users providing numbers for environment variables. Casting them to strings before storing internally
If someone tries to do either of the following:
```js
// .projenrc.js
project.tasks.addEnvironment('LINT_THRESHOLD', 9);
```
```python
project.tasks.add_environment('LINT_THRESHOLD', 9)
```
They'll get the following error on synthesis:
```
if (value.startsWith("$(") && value.endsWith(")")) {
^
TypeError: value.startsWith is not a function
at RunTask.resolveEnvironment (/Users/.../node_modules/projen/lib/task-runtime.js:196:23)
at new RunTask (/Users/.../node_modules/projen/lib/task-runtime.js:73:25)
at TaskRuntime.runTask (/Users/.../node_modules/projen/lib/task-runtime.js:52:9)
at Pip.installDependencies …
```
> fix(tasks): Handle non-string task env vars

- .projen/tasks.json
- docs/api/API.md
- src/javascript/node-package.ts
- src/task-runtime.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/node-package.test.ts
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Spawning a task allows end users to hook into the dependency installation process and increases flexibility
This aligns node and python projects on the same dependency installation API. For node projects, had to explicitly exclude the `install` and `install:ci` tasks from being included in `package.json` scripts to prevent infinite loops.
---
> chore(node-package): Use tasks for installing dependencies

- src/javascript/node-project.ts
- src/release/publisher.ts
- test/javascript/node-project.test.ts
- test/release/__snapshots__/release.test.ts.snap
It has been a while that workflows generated by projen would have warning when running about deprecation of `set-output`
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Last week a new version of `aws-actions/configure-aws-credentials` is [released](https://github.com/aws-actions/configure-aws-credentials/releases/tag/v2.0.0) in which it has solved this issue.
This change will upgrade this action to version 2
---
> chore: updated Configure AWS Credentials action version

- docs/api/API.md
- src/docker-compose/docker-compose-render.ts
- src/docker-compose/docker-compose-service.ts
- test/docker-compose/docker-compose.test.ts
Allows an entrypoint to be defined in a docker-compose service.
---
> feat(docker-compose): support entrypoint

- .eslintrc.json
- docs/api/API.md
- src/javascript/eslint.ts
- src/javascript/projenrc.ts
- src/typescript/projenrc.ts
- src/typescript/typescript.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/eslint.test.ts.snap
- test/javascript/eslint.test.ts
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Currently rules targeting the `Projenrc` file are spread between the `Eslint` and `Projenrc` components.
This is quite awkward to manage and also causes unncessary rules to be added for TypeScript Projenrc files and subprojects.
If you are currently using the `Eslint` component explicitly, we recommend to set `lintProjenRc: false` and add all required rules manually.
Also adds a feature `addLintPattern` to add lint patterns after the component has been created.
---
> fix(eslint): deprecate `lintProjenRcFile` in favor of explicitly defining rules via `Projenrc`

- src/github/workflows-model.ts
Hello 👋 firstly, thank you for such an intuitive and easy way to manage projects!
I found this slight issue whilst trying to create a workflow trigger to only occur when a PR is opened and changes occurred in a specific folder, but noticed this wasn't currently possible due to the API available.
The docs for `PushOptions` stated that the `pull_request` event can use these properties (and they are available to use as per the GitHub docs), but `PullRequestOptions` didn't extend `PushOptions`, instead only `PullRequestTargetOptions` did. This PR updates the doc string to include `pull_request_target` and makes `PullRequestOptions` extend `PushOptions`.
---
> fix(github): extend PullRequestOptions to include PushOptions

- docs/api/API.md
- src/javascript/jest.ts
Looks like I used an argument type instead of argument name in one spot of my recent PR #2515 in the JSDocs. I may look at building a test to catch this in the future but since it's Friday, here's a quick fix for the issue I created instead.
---
> chore(javascript): fix invalid arg name in JSDocs

- docs/api/API.md
- src/javascript/typescript-config.ts
Allows us to set `importsNotUsedAsValues` to `error` instead of the default `remove` option - from the [docs](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues):
> This might be useful if you want to ensure no values are being accidentally imported, but still make side-effect imports explicit.
---
> feat(typescript): support `importsNotUsedAsValues`

- docs/api/API.md
- src/javascript/node-project.ts
- src/javascript/upgrade-dependencies.ts
- test/javascript/node-project.test.ts
Similar fix has been put in place for this `release` and `build` workflows in #2399 
---
> fix(node): Upgrade Workflow is missing id-token permission when GitHub OIDC configured

- .projen/deps.json
- .projenrc.js
- package.json
- yarn.lock
Reverts the accidental change of the minimum node version for projen itself. Node 14 is not EOL yet and we will only change the minimum node version a fair time after EOL.
Using projen with a version before Node 16 currently fails with an error like this:
```
error projen@0.69.1: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "14.21.3"
```
---
> fix: projen cannot be used with node "< 16.0.0"

- docs/api/API.md
- src/cdk/jsii-project.ts
- src/release/publisher.ts
- src/release/release.ts
- test/cdk/jsii.test.ts
Currently the `workflowContainerImage` doesn't get propagated to the `package` or `release` jobs
This PR makes sure that in `jsii-project` when creating the `package-[language]` jobs we set `container` in `extraJobOptions` if present.
It also makes sure when instantiating a `Release` object we can pass it to `release_[language]` jobs.
Both of these jobs currently propagate `workflowRunsOn` to them so the precedent is there.
---
> feat: add `workflowContainerImage` to `Publisher`

- src/cli/index.ts
- src/util.ts
- test/util.test.ts
The filesystem root check in the custom findUp implementation did not account for windows paths.
This was introduced in #2418 
Manually verified the fix on my windows machine.
This is blocking when a new project is created.
Existing projects were only partially affected, as the cli would have successfully found a projen directory unless run outside a projen dir. But there it would have errored anyway.
Fixes #2574
---
> fix(new): cli fails on windows with RangeError

- docs/api/API.md
- src/build/build-workflow.ts
- src/github/index.ts
- src/github/task-workflow.ts
- src/github/workflow-actions.ts
- src/github/workflow-jobs.ts
- src/javascript/upgrade-dependencies.ts
This helps users to create custom workflows that are compatible with different project configurations.
Previously users were forced to copy and paste or manually re-create these steps.
The change itself is to simply export the existing `WorkflowActions` utility class.
Additionally the code the create a pull request from a patch artifact was pulled out into a new helper class and also made available.
These actions are already widely used in the code base and any change would cause existing tests to fail, therefore no additional tests were added.
---
> feat(github): expose GitHub Actions workflow helpers

- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
Some of `jestConfig` properties are not able to update through constructor
because of a bug by assigning hard coded default values.
This commit fixes the bug to assign hard coded values only if the same
properties are not set.
---
> fix(jest): cannot set `preset` and `globals` config when using in a typescript project

- docs/api/API.md
- src/github/workflow-actions.ts
- src/github/workflow-jobs.ts
- src/javascript/upgrade-dependencies.ts
BREAKING CHANGE: To align the `PullRequestFromPatchOptions` interface with the newly introduced feature, two options have moved:\
`PullRequestFromPatchOptions.patch.workflowName` -> `PullRequestFromPatchOptions.workflowName`, `PullRequestFromPatchOptions.ref` -> `PullRequestFromPatchOptions.patch.ref`.
---
Note that the breaking feature was only released yesterday, and is unlikely to already be widely adopted.
---
> feat(github)!: add createPullRequest Workflow Action to create PRs without using a patch

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .projenrc.js
Use Node 16.14 version for github workflows.
---
> chore: use node 16.14 version for github workflows

- docs/api/API.md
- src/java/maven-packaging.ts
It can be useful to know the location of the dist dir, eg. for setting up local dependencies in a monorepo (ref: https://github.com/aws/aws-prototyping-sdk/pull/358 )
This change exposes it as a readonly property.
---
> feat(java): expose readonly maven packaging dist dir

- docs/api/API.md
- src/javascript/node-package.ts
- src/javascript/util.ts
- test/javascript/node-package.test.ts
Ref: https://github.com/projen/projen/pull/2607#discussion_r1177611408
Defines:
- Generic `tryResolveDependencyVersion` javascript/util utility for locating and reading a package version from a given dependencies package.json manifest.
- A public method `NodePackage.tryResolveDependencyVersion` that checks for a semantically valid (i.e, not '\*') dependency version via `project.deps`. If not found it will fallback on the `tryResolveDependencyVersion` utility from above.
Also refactors `NodePackage.resolveDepsAndWritePackageJson` to utilize `tryResolveDependencyVersion` (should have no change in behavior in theory).
---
> feat(javascript): generic `tryResolveDependencyVersion` node-package method.

- docs/api/API.md
- src/javascript/typescript-config.ts
- test/javascript/typescript-config.test.ts
This PR brings in the new parameters offered in [TypeScript 5.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html) and implements support for the `extends` field.
The logic for the `extends` maintains backwards compatibility for:
- Existing projects by not writing it if undefined / empty.
- Typescript <5.0 by writing a single relative path if/when only a singular extension is added.
While also allowing for the newly introduced support for multiple bases via an array.
1.  Support for the `bundler` module resolution strategy, which mimics the resolution patterns of modern bundlers.
2.  Addition of new TypeScript 5.0 configuration options and handling of deprecated options:
- `allowImportingTsExtensions`: Allows TypeScript files to import each other with …
> feat(typescript): TypeScript TSConfig 5.0+ parameters, support for TSConfig extends.

- package.json
- src/cli/cmds/new.ts
- src/cli/index.ts
- src/cli/util.ts
- test/new.test.ts
- yarn.lock
After upgrading yargs, it will now display complete help when no commands are provided to `projen new`. (Fixes #2649)
Handle `CliError`s consistently. Style and log through logging instead displaying a stack trace.
---
> fix(cli): improved error messages for `new` command

- CONTRIBUTING.md
Updating the Contributing Guide with a note for Windows users to use WSL instead of Git Bash because of incompatibility with the build script. 
---
> chore: note for windows users regards build script

- src/javascript/util.ts
- test/javascript/node-package.test.ts
- test/javascript/util.test.ts
This PR implements an additional strategy for resolving dependency manifest paths by searching for a `package.json` file under an optionally provided list of paths + the current node processes default resolution paths.
Additionally, it extracts a new utility `tryResolveModuleManifest` from `tryResolveDependencyVersion` that handles applying the available strategies in decreasing order of accuracy (resolve package.json from node's module resolution, resolve from default export, search under given paths, search node default resolution paths).
Closes #2674
---
> feat(javascript): implement additional manifest resolution strategies for packages with no default or package.json exports.

- docs/api/API.md
- src/gitlab/configuration-model.ts
- test/gitlab/configuration.test.ts
cobertura keyword for code coverage report is depreciated and since GitLab 15.0 is replaced by [artifacts:reports:coverage_report](https://gitlab.com/gitlab-org/gitlab/-/issues/344533) https://docs.gitlab.com/ee/update/deprecations.html#artifactsreportscobertura-keyword
---
> fix(gitlab): `artifacts:reports:coverage_report` replaces deprecated `artifacts:reports:cobertura`

- src/javascript/typescript-config.ts
Small fix to correct the `TypeScriptCompilerOptions.emitDeclarationOnly` type.
---
> fix(javascript): correct `TypeScriptCompilerOptions.emitDeclarationOnly` from `true` -> `boolean`

- src/javascript/node-project.ts
- test/javascript/node-project.test.ts
To use `workflowPackageCache` option with `pnpm`,
"Setup pnpm" step must run before "Setup Node.js" step.
This order comes from pnpm's integration documentation: https://pnpm.io/continuous-integration#github-actions
Close #2710
---
> fix(javascript): workflowPackageCache doesn't work with pnpm

- src/smithy/smithy-build.ts
- test/smithy/smithy-build.test.ts
Adds support for the `sources` property: https://smithy.io/2.0/guides/building-models/build-config.html
---
> feat(smithy-build): support for sources

- docs/awscdk-construct.md
These old properties are marked as `deprecated` in https://github.com/projen/projen/blob/main/src/cdk/jsii-project.ts
---
> chore: fix JSII publishing properties in docs

- src/typescript/typescript.ts
Instead use any provided patterns and then add to it.
Related to #2733 
---
> fix(typescript): `jestConfig.testMatch` is ignored

- docs/api/API.md
- src/version.ts
- test/release/bump.test.ts
Use explicit `path` for `ReleasableCommits`.
Note that the previous PR was merged in error and has not been released since I have cancelled the workflow, so this is not breaking.
#2758
> chore(release): fixup ReleasableCommits API

- src/version.ts
- test/release/bump.test.ts
Using `-E` with `git log` requires the use of [POSIX Extended Regular Expressions](https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions) which comes with certain limitations.
The previous code wrongly assumed that `-P` flag (Perl Regex) is used, but that is not guaranteed to be available on all versions of git.
The use of the POSIX-Extended incompatible values `\r\n` resulted in commit messages containing `r` or `n` being ignored.
---
> fix(release): selective bump ignores commits with 'r' and 'n'

- .github/workflows/upgrade-main.yml
- src/github/workflow-actions.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
When building `RUN_URL` in worklflow-actions, use the `github.server_url` ([source](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context))
context variable. This will allow the URL to be correct on GitHub
Enterprise installations as well as github.com.
This PR was tested locally in a private GitHub Enterprise environment.
---
> fix(github): `RUN_URL` in workflow created PR does not use GitHub enterprise URL

- docs/api/API.md
- src/javascript/node-package.ts
- src/javascript/upgrade-dependencies.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/upgrade-dependencies.test.ts
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Given 
```ts
depsUpgradeOptions: {
types: [DependencyType.PEER],
}
```
Would produce:
```console
npm-check-updates --dep peer --upgrade --target=minor
yarn upgrade
```
However, when `yarn upgrade` executes, the peer deps aren't upgraded because peer dependencies aren't installed by default. This causes [failures](https://github.com/cdk8s-team/cdk8s-hasura/actions/runs/5698912124/job/15447288139?pr=177) such as:
```console
build » compile | jsii --silence-warnings=reserved-word
Error: Error: Declared dependency on version ^2.24.0 of cdk[8](https://github.com/cdk8s-team/cdk8s-hasura/actions/runs/5698912124/job/15447288139?pr=177#step:5:9)s, but version 2.23.0 was found
```
Projen actually automatically adds peer dependencies as dev dependencies as well. This means we need to also produce: …
> fix(upgrade-dependencies): upgrade command doesn't consider requested types

- src/javascript/node-package.ts
- test/javascript/node-project.test.ts
npm has removed the support for this flag in npm version 7 (https://docs.npmjs.com/cli/v7/using-npm/changelog#v7111-2021-04-23). The npm version for node 18 and above errors on setting this flag.
---
> fix(node-project): updated code artifact login script to work for node version above 16

- docs/api/API.md
- src/renovatebot.ts
- test/renovatebot.test.ts
**Issue**:
> I'm trying to
>```
>const renovateJs = project.tryFindObjectFile('renovate.json5');
>renovateJs?.patch(
>   JsonPatch.add('/', {
>     postUpgradeTasks: {
>       commands: ['npx projen'],
>       executionMode: 'branch',
>     },
>   }),
> );
> ```
> but it looks like the first line isn't finding the renovate.json5 file. I was wondering: is tryFindObjectFile reading the .json5 suffix and tanking? I thought "ok, I'll just rename it to renovate.json which is supported: https://docs.renovatebot.com/configuration-options/, but... it's not obvious where I'd do that.
**Cause**: The configuration file was created in the `preSynthesize` stage to ensure that all dependencies are available in for the renovatebot configuration to consider. This doesn't work with file escape hatches, …
> fix(renovatebot): cannot use file override for renovate.json5

- src/cli/util.ts
- test/new.test.ts
Turns out `--save-dev` doesn't overwrite a `save=false` in other npm configs like one might expect.
Passing `--save --save-dev` however does overwrite any config and correctly saves the package as dev dependency.
Fixes #2837
---
> fix(new): projen new --from fails with "Unable to resolve package name from spec" error with "save=false" in .npmrc

- src/cli/cmds/new.ts
- test/new.test.ts
`projen new` by default initialises a git repository using hard coded default branch name `main`. Some organisations / users may have different defaults for git branch (like `mainline`) and so git since version 2.28 provides global option [init.defaultBranch](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch). This PR makes `projen new` to respect that setting when present.
---
> fix(cli): respect git init.defaultBranch

- docs/api/API.md
- src/javascript/typescript-config.ts
Added missing TypeScript parameters `exactOptionalPropertyTypes` and `useUnknownInCatchVariables` to the the definition file
---
> feat(typescript): Added missing TypeScript compilerOption parameters

- src/gitlab/configuration.ts
- test/gitlab/configuration.test.ts
Fixing the issue of the job `id_tokens` rendering into a snake case, while not respecting the original format.
---
> fix(gitlab): add uppercase support for idTokens

- docs/api/API.md
- docs/awscdk.md
- src/awscdk/awscdk-app-ts.ts
- src/awscdk/awscdk-construct.ts
- src/awscdk/integ-runner.ts
- test/__snapshots__/inventory.test.ts.snap
- test/awscdk/awscdk-app.test.ts
- test/awscdk/awscdk-construct.test.ts
This PR introduces preliminary and experimental support for `integ-runner` integration tests in AWS CDK TypeScript projects.
---
> feat(awscdk): add experimental integ-runner support

- docs/api/API.md
- src/javascript/node-package.ts
- test/javascript/node-package.test.ts
NodePackage are synthesising all dependencies during `preSynthesize` phase rather than during `synthesize` (as projen philosophy dictates). This results that any components added after NodePackage (that means almost all of them in normal situation of using NodeProject) cannot make any changes to dependencies during their `preSynthesize` (that changes will be silently ignored).
However, ability for components to make dependencies changes during `preSynthesize` are crucial to not require specific components order. For example a component (i.e. implementing [BrowsersList](https://github.com/browserslist/browserslist) config) wants to add a dev dependency (i.e. [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features)) only if another …
> fix(node-package)!: components cannot change deps at preSynthesize stage

- README.md
Updates README to replace deprecated property usage and highlight the availability of Python version of projen.
---
> chore(docs): update Python related information in README

- src/python/poetry.ts
- test/python/__snapshots__/poetry.test.ts.snap
- test/python/poetry.test.ts
Python projects with Poetry as a dependency manager are silently ignoring all dependencies without explicit version. This PR fixes that by adding `*` fallback according to [Poetry docs](https://python-poetry.org/docs/managing-dependencies/)
---
> fix(poetry): add version fallback

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .projen/deps.json
- .projenrc.js
- docs/api/API.md
- package.json
- src/awscdk/awscdk-construct.ts
- src/awscdk/lambda-function.ts
- src/cdk/jsii-project.ts
- src/release/publisher.ts
- src/release/release.ts
- src/web/next.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/awscdk/__snapshots__/lambda-function.test.ts.snap
- test/awscdk/awscdk-construct.test.ts
- test/awscdk/lambda-function.test.ts
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- yarn.lock
Upgrade Node 16.x to 18.x
Using `18.12.0` because it is the first long term support (LTS) version based on the release schedule https://github.com/nodejs/Release/blob/main/schedule.json for v18 on 2022-10-25 from https://nodejs.org/dist/.
Fixes #2979
---
> feat(node): default to Node.js 18.x

- docs/api/API.md
- src/javascript/typescript-config.ts
Adding `types` and `declarationMap` missed fields to the `compilerOptions` of TypeScript config. Providing link to the documentation of that fields.
---
> fix(typescript-config): add `types` and `declarationsMap` missed fields

- docs/api/API.md
- src/vscode/extensions.ts
- src/vscode/launch-config.ts
- src/vscode/settings.ts
This PR exposes VSCode related JSON files as `.file` properties on appropriate components.
This will allow to use `.patch` and `.addToArray` method of ObjectFile for advanced customisations (as all those files are created lazily using `project.tryFindObjectFile` may not be a viable alternative currently).
---
> feat(vscode): expose configuration files as `.file` property

- src/cli/tasks.ts
- test/cli.test.ts
A common use case for tasks is to act as proxies to other CLIs/tools (e.g. pip, poetry, etc). The current behavior of displaying projen's own help document for the `--help` flag for tasks prevents the proper passthrough of `--help` flags that are intended for the downstream tool (when `receiveArgs` is true).
The help document shown for tasks is fairly generic and can't be customized for tasks anyway.
I considered adding an option to the task itself (e.g. `disableHelp: boolean`) to control this behavior, but this current implementation makes more sense to me since `receiveArgs` should really mean all args. I realize that `--inspect` will still be captured by projen, but that one actually does make sense since a) it's not a standard flag on most tools and b) the return value is useful for …
> fix(cli): pass through --help flag for tasks that receive args

- docs/api/API.md
- src/component.ts
- src/project.ts
- test/constructs.test.ts
Change the implementations of `project.subprojects`, `project.root`, `project.components` and `projects.files` to operate of the construct tree instead of arrays.
Addresses parts of #3056
---
> fix: construct tree not used internally

- src/release/bump-version.ts
- test/release/bump.test.ts
If minMajorVersion is specified the first release should be taking the minMajorVersion into account instead of defaulting to 0.0.0. 
---
> fix(release): first release ignores minMajorVersion

- package.json
- yarn.lock
Update jsii-docgen to latest version. This gives us some improvements to the generated API.md file and will also allows in future to create language and submodule specific docs.
---
> chore(docs): upgrade jsii-docgen to latest version

- src/object-file.ts
- test/object-file.test.ts
`ObjectFile.addToArray` method is overriding all previous calls values when called on a non-existent array (see added regression test). This PR fixes that.
---
> fix(object-file): addToArray overrides all previous calls on non-existent array

- src/_resolve.ts
- src/javascript/eslint.ts
- src/object-file.ts
- test/object-file.test.ts
With current implementation ObjectFile (and all it subclasses) are throwing on encountering any perfectly valid Javascript boxed primitives in the object values (for example `new Sting('something')` or `new Boolean(something)`) even while those values may be stringified by `JSON.stringify` (the serialisation function that we are using) without any problem. This PR fixes that.
In addition, there are several JavaScript built-in objects that while having some limitations on JSII are very useful either for internal usage or for TS/JS-first usage of projen, however, those classes are missing built-in `.toJSON` method and so also resulting in throw from ObjectFile, particularly RegExp, Set and Map. This PR proposes to fix that by resolving RegExp (without flags) into its string source, Set into …
> fix(object-file): allow boxed primitives, Set, Map and RegExp in values

- test/__snapshots__/new.test.ts.snap
I'm kinda confused why #3088 didn't fail and the release did: https://github.com/projen/projen/actions/runs/6773601370/job/18408831034
But here's the fix.
---
> fix(yarn): fixup snapshot for yarn up (#3088)

- src/python/poetry.ts
- src/python/setuppy.ts
- test/python/__snapshots__/poetry.test.ts.snap
- test/python/poetry.test.ts
BREAKING CHANGE: Python >=3.8 is now required for projen and consequently for all projects. Upgrade to a supported Python version.
---
> feat(python)!: default python version is now python >=3.8

- CONTRIBUTING.md
In the Release Versioning paragraph the default branch which this works from now is renamed to `main` and we want the document to reflect that. 
* fix: changed master->main in version bump explainer paragraph
---
Thank you for your open source project. 
> chore: fix CONTRIBUTING.md referring to wrong default branch

- src/renovatebot.ts
- test/__snapshots__/renovatebot.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
> fix(renovate): preset config:base is now called config:recommended

- .gitignore
- .projenrc.js
chore: this PR adds a gitignore rule to exclude asdf's .tool-versions local configuration file.
---
> chore: add gitignore rule for asdf's .tool-versions file

- src/typescript/projenrc.ts
- test/typescript/projenrc.test.ts
Fixes https://github.com/projen/projen/issues/3248
---
> fix(typescript): projenrc.ts for TS projects is not excluded from npm package

- docs/introduction/index.md
This PR removes a reference to `.NET` from the introduction page.
Under the [What is projen?](https://projen.io/docs/introduction/#what-is-projen) section, first paragraph, we reference .NET.
**Before:**
> Projen can be used with TypeScript, Python, Java, **.NET** and Golang.
**After:**
> Projen can be used with TypeScript, Python, Java and Golang.
---
> chore(docs): remove .NET from the introduction

- docs/introduction/index.md
In this small PR, I am proposing that we update the doc's [introduction](https://projen.io/docs/introduction/) by breaking up the project types with headers. This will make it easier for developers to scan the list and identify the relevant project types.
---
> chore: Improve readability of project types on docs Introduction page

- .github/workflows/release.yml
- src/github/workflow-steps.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
A stray `'` made it's way into the codebase in #3252, causing the release workflow to fail.
This is currently blocking the release of projen. Which is good, because it means the broken code did not get published.
I don't know of a better way to catch these kind of mistakes. =/
---
> fix(release): workflow is failing because of invalid bash command

- src/ignore-file.ts
- src/util.ts
- test/util.test.ts
Related to #3284
The issue could be related to more components, and this PR doesn't fully resolve it.
Normalize gitignore paths to be consistent across platforms. This avoids the diff shown between Windows (\/) and Linux (/) directory separators.
---
> fix(gitignore): paths separators are inconsistent for cross platform development

- src/github/github-credentials.ts
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
Bump version of action so it uses node20 instead of node16
---
> fix(github): bump version of tibdex/github-app-token action; resolves runtime deprecation warnings

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- docs/api/github.md
- src/build/build-workflow.ts
- src/github/workflow-actions.ts
- src/github/workflow-steps.ts
- src/release/publisher.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/build/__snapshots__/build-workflow.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/task-workflow.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Update artifact-related github actions that are generating warnings in projects due to nodejs 16 being deprecated in github actions runners.
v4 of actions/upload-artifact [introduced](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) some breaking changes, so we've set `overwrite` to be true by default to mirror the previous behavior as closely as possible.
---
> fix(github): bump upload/download artifact actions to v4; resolves runtime deprecation warnings

- src/github/github-credentials.ts
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
In PR #3338 we attempted to update the version of the `tibdex/github-app-token` GitHub Action to a later version.
We incorrectly picked the latest commit from the main branch of this action. However that's not how most GitHub Actions work. Instead they a tag a dangling commit that has been specially created with the required build artifacts.
This PR we are updates the hash to the correct working version as referenced from the release page: https://github.com/tibdex/github-app-token/tree/v2.1.0
Fixes: https://github.com/projen/projen/issues/3340
---
> fix(github): invalid commit for tibdex/github-app-token action

- .projen/tasks.json
- src/javascript/upgrade-dependencies.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/cdk8s/cdk8s-app-project-ts.test.ts
- test/javascript/upgrade-dependencies.test.ts
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/typescript/typescript.test.ts
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
When `some-dep@^10` is added as a dependency, it is incorrectly included in the list of to-be-upgraded dependencies. This was due to a bug in a boolean expression; with the the code comment stating the clear intention to exclude them.
The reason for this is that ncu would upgrade `some-dep@^10` to a later version. But `projen default` would then revert back to the version defined in code.
While fixing the issue, I realized that while we need to exclude these deps from ncu, we still want them to be included in the package manager upgrade command, so that they receive the latest version for the given version constraint.
---
> fix(upgrade-dependencies): unnecessary attempts to upgrade versions in package.json

- .github/workflows/build.yml
- .github/workflows/check-licenses.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- src/github/workflow-steps.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/build/__snapshots__/build-workflow.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/task-workflow.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
See: https://github.com/actions/checkout/releases/tag/v4.0.0
Related to https://github.com/projen/projen/issues/3337
---
> fix(github): bump version of actions/checkout to v4; resolves runtime deprecation warnings

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- src/github/workflows.ts
- src/javascript/node-project.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/awscdk/awscdk-construct.test.ts
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
See: https://github.com/actions/setup-node/releases/tag/v4.0.0
Related to https://github.com/projen/projen/issues/3337
---
> fix(github): bump version of actions/setup-node to v4; resolves runtime deprecation warnings

- .github/workflows/build.yml
- .github/workflows/release.yml
- src/github/workflows.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
See: https://github.com/actions/setup-python/releases/tag/v5.0.0
Related to #3337
---
> fix(github): bump version of actions/setup-python to v5; resolves runtime deprecation warnings

- src/javascript/jest.ts
- src/javascript/node-package.ts
- src/project.ts
- src/typescript/typescript.ts
Related to #3284 
1. I found that paths were changing between Windows and WSL in a `TypeScriptProject` that uses Jest. I updated it to use `normalizePersistedPath`. It occurs when the jest `testdir` has the prefix `src/` like in `src/tests`.
1. For this case, I tested locally in the project that I mentioned and it worked correctly, using POSIX separators (/) in both WSL and Windows. No test were added.
1. Also, I searched for the duplicated of the logic in `normalizePersistedPath`, which currently is only the regex matching of `/\\/g`.
1. I didn't test this one. I think it's safe.
1. If the change is accepted, I think there is room to create an Eslint rule for semantics in case a similar logic is used. That would be in a separate MR, but something along the lines:
```typescript
const …
```
> fix(jest): directory separators are inconsistent for cross platform development

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- .projenrc.js
- src/release/publisher.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/release.test.ts
By looking into [projen in NPM](https://www.npmjs.com/package/projen), I noticed that it didn't have the provenance widget in the page. Then, looking into the [Github action run](https://github.com/projen/projen/actions/runs/7942036715/job/21685009089), I verified that it wasn't generated.
I realized, I made a mistake in [#3300](https://github.com/projen/projen/pull/3330) because the value `true` should be quoted in YAML. 
Before, wrong
```yaml
- name: Release
env:
NPM_DIST_TAG: latest
NPM_REGISTRY: registry.npmjs.org
NPM_CONFIG_PROVENANCE: true
NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
After, correct
```yaml
- name: Release
env:
NPM_DIST_TAG: latest
NPM_REGISTRY: registry.npmjs.org
NPM_CONFIG_PROVENANCE: "true"
NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
I tested this fix in one of my projects …
> fix(release): provenance statement not being generated because of missing quotes in YAML

- src/javascript/util.ts
Related to https://github.com/projen/projen/issues/3284#issuecomment-1964163891
This is the second attempt at fixing the directory separator issue for lambda entrypoints, which was started in https://github.com/projen/projen/pull/3387. 
I tried adding unit tests for `renderBundleName`. Unfortunately, this can't be unit-tested now because NodeJS exports the `path` package for the Linux platform instead of Windows at import time and not at runtime.
https://github.com/nodejs/node/blob/f28ccd3941e70a825786eff7e28f59014ac76ac9/lib/path.js#L1546
I tested it locally in an example project, and it looks like it's fixed now.
---
> fix(node): some directory separators are still inconsistent between platforms in tasks.json and package.json

- docs/api/javascript.md
- src/javascript/typescript-config.ts
- test/__snapshots__/new.test.ts.snap
This is adding support for `compilerOptions` used [in the wild](https://github.com/tsconfig/bases/blob/main/bases/strictest.json) and escape hatches had to be used.
This was found when applying [@tsconfig/strictest](https://github.com/tsconfig/bases?tab=readme-ov-file#strictest-tsconfigjson) and working around TypeStrong/ts-node#1958 (merged, but not yet released, a year later)
No issue was created, and no tests were added. This is merely a pass-thru to tsconfig (like the existing options above them in the code).
---
> fix(tsconfig): support three missing strict tsconfig `compilerOptions`

- docs/concepts/projects/building-your-own.md
- src/javascript/node-project.ts
Fixes
prMention missing in the MyMicroserviceProjectOptions interface
defaultReleaseBranch shouldn't be there in the example because this example should solely help with the goal of adding new prMention property, not dragging in what the default options the parent class has.
---
> chore: fix missing type in building your own project docs

- docs/api/javascript.md
- src/javascript/typescript-config.ts
- test/javascript/typescript-config.test.ts
Fixes #3411
Note: Still unable to make an empty `compilerOptions` (without providing one with everything explicitly set to `undefined`) due to `TypeScriptProject` forcing an override. I'll make another issue and PR for that.
Apologies to @coleHafner if they've already spent time on this
---
> fix(typescript): TSConfig `compilerOptions` can be optional

- src/cli/cmds/new.ts
Fixes the issue that users frequently struggle to discover the project type specific help screen.
---
> fix(cli): call-out command to see project type specific help

- .projen/tasks.json
- .projenrc.ts
Doesn't fix a current bug, but will help with windows support.
Instead of `bash`-isms that aren't portable (`echo ... | cat - ... | tee ... > /dev/null`) use `--banner:js=` and `--footer:js=` built-in capabilities of `esbuild`.
The resulting `lib/run-task.js` is identical in both cases.
Aside: it would be nice if we could use the work we've done in `Bundler` but alas, it doesn't give us control of the name of the task or where the output goes.
---
> chore: make `bundle:task-runner` use single esbuild command

- src/javascript/node-project.ts
- test/javascript/node-project.test.ts
This is important because https://bun.sh is not only a npm alternative, but also a node and npx alternative.
Systems with bun installed may not have node or npm, but if `NodePackageManager.BUN` is chosen, we do know that `bun` is available, and can print the `PATH` that way.
Fixes #3490 
---
> fix(bun): `npx` used when `bun` is package manager to print `PATH`

- src/javascript/node-project.ts
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/node-project.test.ts
Followup to #3449.
As pointed out by [this comment](https://github.com/projen/projen/pull/3449/files/5b3b3492ae87436dc7566d2f46016ebc5e44d6e6#r1551681459), the `...buildWorkflowOptions` spread was passed to in the wrong place relative to `preBuildSteps` which should contain both setup/install steps plus provided step. So `buildWorkflowOptions.preBuildSteps` was overriding the setup/install steps.
---
> fix(node): build workflow options pre build steps configuration overriding setup steps

- src/web/react.ts
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Fixes # NA
This PR moves the `react-scripts` dependency from the "deps" to the "devDeps".
react-scripts is not required to be a dependency of the project given that it's a dev tools that it's not bundled together with the rest of the project dependencies.
This also helps to address potential false positive that derive from `npm audit` command which can be instrumented to inspect only `--production-only` dependencies [ref](https://github.com/facebook/create-react-app/issues/11174)
---
> fix(web-react): react-scripts incorrectly listed as dep; should be devDep

- docs/integrations/github/index.md
I found that the instructions for setting up the github actions via a github app were not quite a clear as they could have been, so raising this change to help clarify it.
---
> chore(docs): improve how to set up a a github app for projen 

- docs/api/awscdk.md
- docs/api/cdk.md
- docs/api/cdk8s.md
- docs/api/cdktf.md
- docs/api/javascript.md
- docs/api/typescript.md
- docs/api/web.md
- src/javascript/node-project.ts
- test/__snapshots__/inventory.test.ts.snap
Partially addresses: #3304
BREAKING CHANGE: by default `projen` will not be installed in subproject directories. To install `projen` in a subproject directory, explicitly set `projenDevDependency: true` in the subproject.
Installing projen in sub-projects leads to weird behavior where the sub-project is referencing different source than the parent project - which breaks things like `instanceof` expressions when the two class objects are from different sources. I think it makes more sense to only install a single copy of `projen` for an entire project graph.
I suspect that enabling sub-project installation by default was an oversight originally since it makes sense to have that default for the root project. So I think its safe to consider this a non-breaking change since the default will …
> fix(subprojects)!: conflicting projenDevDependency is added to subprojects by default

- src/javascript/node-project.ts
- test/__snapshots__/integ.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
Fixes #1933
`npm pack --pack-destination` is supported by v7+. The `minNodeVersion` of projen is [v16.0.0](https://github.com/projen/projen/blob/a4de88eeeb06f9465e063653abee9fa116fcd361/.projenrc.ts#L90) which is [shipped with npm v7.x](https://nodejs.org/en/blog/release/v16.0.0). Happily we can use `--pack-destination` because it is now supported by active npm versions😃. 
---
> fix(node): use `--pack-destination` instead of `mv`

- docs/publishing/publisher-component.md
I was reviewing the documentation for [publishing to AWS CodeArtifact](https://projen.io/docs/publishing/publisher-component#publishing-to-aws-codeartifact), and noticed the existing guidance is to leverage static AWS access keys. This was fairly surprising, so I doubled checked Projen's source code and found [configuration options that allow GitHub OIDC to be used for CodeArtifact auth](https://github.com/projen/projen/blob/5cf621a0e4716da2bc26d06a1c8e1b9437ff06ec/src/release/publisher.ts#L974-L1014).
IMO Projen should recommend this approach instead of static credentials. I've performed a small edit of the `Publishing to AWS CodeArtifact` section that includes this guidance, as well as an example.
As a sidenote, this documentation is likely to be viewed by folks who are bit by [GitHub …
> chore(docs): documentation for GitHub OIDC usage when authenticating to CodeArtifact

- src/task-runtime.ts
Related to #https://github.com/projen/projen/issues/3384
I was getting the following error when running `yarn post-compile` in the projen repository:
```bash
❯ yarn post-compile
yarn run v1.22.19
$ node ./projen.js post-compile
👾 post-compile » docgen | jsii-docgen .jsii -o docs/api/projen --split-by-submodule
👾 post-compile » readme-macros | shx mv README.md README.md.bak
👾 post-compile » readme-macros | cat README.md.bak | markmac > README.md
'cat' is not recognized as an internal or external command,
operable program or batch file.
👾 Task "post-compile » readme-macros" failed when executing "cat README.md.bak | markmac > README.md" (cwd: D:\Workspace\projen)
Failed to execute command: node bin/projen post-compile Error: Command failed: node bin/projen post-compile
at checkExecSyncError …
```
> fix(task-runtime): call cat command with shx on Windows

- docs/api/gitlab.md
- src/gitlab/configuration-model.ts
The WorkflowRule has the type JobWhen for the when field. When in a workflow rule can be only `always` and `never`: https://docs.gitlab.com/ee/ci/yaml/#workflowrules
If used in jobs it could have more inputs: https://docs.gitlab.com/ee/ci/yaml/#when
---
> fix(gitlab): use WorkflowWhen in WorkflowRule

- src/github/workflows.ts
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
Resolves runtime deprecation warnings.
---
> fix(github): bump version of actions/setup-dotnet to v4

- .github/workflows/build.yml
- .github/workflows/release.yml
- projenrc/windows-build.ts
- src/github/workflows.ts
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
Resolves runtime deprecation warnings.
---
> fix(github): bump version of actions/setup-go to v5

- .github/workflows/publish-docs.yml
Resolves runtime deprecation warnings.
https://github.com/projen/projen/actions/runs/9254951219
https://github.com/actions/upload-pages-artifact: v2 to v3
https://github.com/actions/deploy-pages: v3 to v4
---
> chore(docusaurus): bump versions of pages actions

- src/web/next.ts
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
Fixes https://github.com/projen/projen/issues/3442
As far as I understand tsconfig.dev.json will only used for projen synthing, so that the module could switch to commonjs without effecting the standard tsconfig for nextjs.
Another approach could be to switch to `npx tsx .projenrc.ts ` as default task for projen (https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#im-using-tsx)
---
> fix(next): use module commonjs for dev tsconfig

- docusaurus/src/pages/index.js
In #3606 we moved the Getting Started page to a different location.
Docusaurus as a detector for broken links, but that seems to not include HTML documents like the landing page.
So unfortunately those links did not get updated.
Fixes #3618
---
> chore: fix getting started links on landing page

- .eslintrc.json
- src/javascript/eslint.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/eslint.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Fixes https://github.com/projen/projen/issues/3415
---
> fix(eslint): use import/no-duplicates instead of no-duplicate-imports for eslint

- docs/api/projen.md
- src/task-runtime.ts
- test/tasks/runtime.test.ts
Fixes https://github.com/projen/projen/issues/3493
---
> fix(task-runner): task env vars handed to spawn no longer get left behind

- .github/workflows/build.yml
- src/cdk/consts.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
Fixes #3687
BREAKING CHANGE: Aligns SDK versions used in the package GitHub Actions Workflows to the [official JSII superchain](https://github.com/aws/jsii/blob/v1.101.0/superchain/README.md#included-language-sdks) versions. Use low-level [Object File Patches](https://projen.io/docs/concepts/escape-hatches#object-file-patches) to revert to previous versions.
---
> feat(jsii)!: upgrade jsii toolchain sdks

- .github/workflows/release.yml
- src/release/publisher.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
Pull request #3688 was insufficient to properly fix #3687
Aligns SDKs to the JSII superchain for publishing jobs too.
Fixes #3687
---
> feat(publisher)!: update jsii toolchain sdks

- .github/workflows/build.yml
- .github/workflows/release.yml
- src/cdk/consts.ts
- src/github/workflows.ts
- src/release/publisher.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
Fixes #3707
We tried upgrading the version of java in https://github.com/projen/projen/pull/3688 and https://github.com/projen/projen/pull/3694, however this caused failing Maven releases due to an apparent incompatibility with nexus-staging-maven-plugin used by publib.
Tested here: https://github.com/projen/canary-testing/actions/runs/9844843704/job/27179142549
BREAKING CHANGE: Changes the OpenJDK Java version used in the Publisher GitHub Actions Workflow to Amazon Corretto and Java 11. Use low-level [Object File Patches](https://projen.io/docs/concepts/escape-hatches#object-file-patches) to change to other versions.
---
> fix(publisher)!: cannot publish to Maven due to release plugin incompatible with workflow jdk

- .github/workflows/build.yml
- projenrc/windows-build.ts
Changes the build matrix to require the Windows test to pass.
Doing this mainly by setting the `continue-on-fail` condition to false for windows build.
Also changes the semantic from "experimental" builds to a "primary" build that does extra stuff and explicitly (dis-)allowing builds to fail.
---
> chore(ci): require windows build to pass

- .github/workflows/build.yml
- .projen/tasks.json
- projenrc/windows-build.ts
- src/cdk/jsii-project.ts
- src/github/util.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
Fixes the failing packaging step in windows builds.
Instead of a complex bash expression, this now leverages  a feature of the projen task runner.
- Firstly, replacing the `if` statement with task step conditions 
- Secondly, use `node` to check if we are in CI. Unlike bash commands, node should always be available
- Thirdly, installing `rsync` on windows runners
Additionally this reverts the special treatment of packaging in Windows builds.
Resolves #2761
---
> fix(jsii): running `projen package` on windows fails

- src/typescript/typescript.ts
- test/javascript/jest.test.ts
This accidentally slipped through in #3637
Fixes #3735
---
> fix(typescript): Jest `testMatch` doesn't match compiled JS files

- docs/api/gitlab.md
- src/gitlab/configuration-model.ts
- src/gitlab/configuration.ts
- test/gitlab/configuration.test.ts
Adds the missing default configuration option for `id_tokens` as documented in [Gitlab docs](https://docs.gitlab.com/ee/ci/yaml/#default).
---
> feat(gitlab): support for `default.id_token` configuration

- src/github/pull-request-backport.ts
- test/github/__snapshots__/pull-request-backport.test.ts.snap
Fixes #3751
Adds a custom check to manually check if the targeted PR has the required labels.
If no labels are found, the backport action is bypassed, and thus keeps the status green.
Workflow tested here: https://github.com/projen/canary-testing/blob/main/.github/workflows/backport.yml
Result: https://github.com/projen/canary-testing/pull/12
---
> fix(github): backports make most PRs look like they've failed checks

- .projen/tasks.json
- src/release/publisher.ts
- src/version.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/release/bump.test.ts
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/version.test.ts
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
Fixes https://github.com/projen/projen/issues/2427
The `!` mark is used in bash because is interpreted by the `test` command. Because `test` doesn't exist in Windows cmd, then running the bump task fails. It turns out that `grep` has a flag `-v` to invert the match and works both in bash and cmd, and it solved the problem. Refactored the `publishTask.condition` to use the same expression. Added a test to check the correct handling of a release commit with message `chore(release):`.
---
> fix(bump): exclamation operator `!` is not recognized when running bump on windows

- docs/api/projen.md
- src/dependencies.ts
- src/javascript/node-package.ts
- src/javascript/node-project.ts
- test/cdktf/cdktf-construct.test.ts
- test/deps.test.ts
- test/javascript/node-project.test.ts
Fixes #3776
Resolves two separate but related issues with dependency handling.
1. peer dependencies have a check to not a build dependency if a runtime dependency already exists
This check made the assumption that no build dependency would exists if a runtime dependency exists.
However when dealing with project inheritance, this can actually happen quite easily.
First fix is to make that check more robust and have peer deps override an existing build dep.
2. projen indiscriminately adds build dependency on `constructs@^10.0.0`.
This is fine, but fails when a project needs to constraint their usage of constructs to e.g. `^10.3.0`. 
The fix is to add a check if there already is a dependency on constructs that fulfills this requirement.
--- …
> fix: projen dev dependency on `constructs` cannot be overridden

- docs/api/javascript.md
- src/javascript/typescript-config.ts
I noticed that `TypescriptConfig` component is missing quite a few number of options from tsconfig. If I were to add them to the component should I use the descriptions from https://www.typescriptlang.org/tsconfig/ page or https://json.schemastore.org/tsconfig?
I couldn't run `npx projen build` locally as `package` task is failing due to some missing dependencies.
---
> fix(typescript): add node10 to moduleResolution enum

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- src/github/workflow-steps.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/build/__snapshots__/build-workflow.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/task-workflow.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
On August 19, 2024 GitHub announced [1] that the default behavior of the `upload-artifact` action will change to not upload hidden files as they might contain sensitive information. On September 2, 2024 this change was released as a new minor version. Because projen does not lock GitHub's first-party actions to a specific release, any workflows that relied on hidden files being uploaded started failing.
As a temporary measure to unblock customers, we are reverting the action to a version. We agree with the changes GitHub has made, we just need a little more time to sort this out in projen.
Fixes #3820
[1] https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/
--- …
> fix: GitHub Workflows failing due to missing hidden files

- .github/workflows/build.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- docs/api/github.md
- src/github/workflow-actions.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/build/__snapshots__/build-workflow.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
On August 19, 2024 GitHub announced [1] that the default behavior of the `upload-artifact` action will change to not upload hidden files as they might contain sensitive information. On September 2, 2024 this change was released as a new minor version. As a temporary measure to unblock customers, projen locked the version of the `upload-artifact` action to a previous version that is compatible with projen, see https://github.com/projen/projen/pull/3822.
This PR changes the default name of the repo patch to not use a hidden file name.
It will currently still be possible to manually specify a hidden file name for the patch file. This will be addressed when projen is switching to the latest action version.
[1] https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breakin …
> fix(github): fails to upload repo patch when using `upload-artifact` >= 4.4.0

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- docs/api/build.md
- docs/api/github.md
- src/build/build-workflow.ts
- src/build/private/consts.ts
- src/github/private/util.ts
- src/github/task-workflow-job.ts
- src/github/util.ts
- src/github/workflow-actions.ts
- src/github/workflow-steps.ts
- src/javascript/node-project.ts
- src/release/release.ts
- test/__snapshots__/integ.test.ts.snap
- test/awscdk/__snapshots__/awscdk-construct.test.ts.snap
- test/build/__snapshots__/build-workflow.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/task-workflow.test.ts.snap
- test/javascript/__snapshots__/node-project.test.ts.snap
- test/javascript/__snapshots__/upgrade-dependencies.test.ts.snap
- test/javascript/node-project.test.ts
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/release/__snapshots__/release.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Previously `WorkflowSteps.uploadArtifact()` would upload hidden files. However this is not advisable as hidden files might contain sensitive information. Recently the upstream GitHub Action `actions/upload-artifact` has addressed this behavior (see https://github.com/projen/projen/pull/3822). 
This change brings the projen helper and all usage inline.
BREAKING CHANGE: In GitHub Actions Workflows, hidden files are not uploaded as part of artifacts anymore. If you are using only standard projen configurations, this change will not affect you. If you have previously relied on uploading hidden files as part of artifacts, we strongly recommend adjusting the workflow. Alternatively, setting `WorkflowSteps.uploadArtifact({ with: { includeHiddenFiles: true } })` will restore the previous …
> feat(github)!: exclude hidden files from artifacts by default

- src/javascript/node-project.ts
- src/typescript/typescript.ts
- test/cdk8s/cdk8s-app-project-ts.test.ts
- test/typescript/typescript.test.ts
Fixes #3846
The `Release` component of `NodeProject` requires the packaging task to be available and functioning. Previously it was possible to configure the project so that `release: true` and `package: false`, causing a failure during the release. This was most prominent in the `TypeScriptAppProject`, which is an opinionated TypeScript project type that basically indicates that the package should not be published. Because it has both `release` and `package` disabled by default, it's easy to just enable releases but not packaging.
---
> fix(typescript): can't release when package is disabled

- docs/quick-starts/typescript/hello-world/index.md
typo in code example for `tsconfig`
---
> chore(docs): fix wrong tsconfig property name in typescript quick-start

- src/javascript/node-package.ts
- test/javascript/node-package.test.ts
Certain versions of npm (at least my tested version, `10.8.2`) silently refuse to bundle a dependency if it doesn't occur in `dependencies`, and `dependencies` only. Specifically, if it also occurs in `devDependencies`, `npm pack` will just silently not bundle the directory.
Add a check for that to prevent users from falling into this trap.
Also add a clarification on the `peerDependencies` check. It makes sense, but it took me longer than should be necessary to understand, and I like the computer to explain things to my peanut-sized brain 😉.
---
> fix: bundledDependencies are silently ignored by NPM

- docs/api/gitlab.md
- src/gitlab/configuration.ts
- test/gitlab/gitlab-configuration.test.ts
This introduces a `path` option to `GitlabConfiguration` and `NestedConfiguration`, giving users the option to produce Gitlab CI configuration and Gitlab CI templates  in the files of their choosing. This is useful for a pattern where we only want to execute a job if known input files or the job definition itself has changed, consider:
```
├── gitlab-ci.yml
├── a
│   ├── job.yml
│   └── input-a
└── b
├── job.yml
└── input-b
```
```
a:
script: []
rules:
changes: b/**/*
b:
script: []
rules:
changes: b/**/*
```
---
> feat(gitlab): add path option to CiConfiguration

- .mergify.yml
- docs/api/github.md
- src/github/auto-merge.ts
- src/github/mergify.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/github/__snapshots__/mergify.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
To address the message from Mergify:
```
‼️ Action Required ‼️
The configuration uses the deprecated commit_message_template attribute of the queue action in one or more pull_request_rules. It must now be used under the queue_rules configuration.
A brownout is planned on September 16th, 2024.
This option will be removed on October 21st, 2024.
For more information: https://docs.mergify.com/configuration/file-format/#queue-rules
‼️ Action Required ‼️
The configuration uses the deprecated merge_method attribute of the queue action in one or more pull_request_rules. It must now be used under the queue_rules configuration.
A brownout is planned on September 16th, 2024.
This option will be removed on October 21st, 2024.
For more information: …
```
> fix(mergify): some parameters are deprecated in `pull_request_rules` and now need to be in `queue_rules`

- docs/api/gitlab.md
- src/gitlab/configuration-model.ts
Fixes #3894 
Adds missing "name" property from GitLab workflow configuration
---
> feat(gitlab): add name to gitlab workflow

- .github/workflows/auto-queue.yml
- docs/api/github.md
- src/github/auto-queue.ts
- test/github/__snapshots__/merge-queue.test.ts.snap
- test/github/merge-queue.test.ts
The AutoQueue workflow cannot use a default github token, because queuing a PR with the default token will not trigger any merge queue workflows. Which just means the PR will not be merged at all.
BREAKING CHANGE: `AutoQueueOptions` now takes an optional `projenCredentials` option instead of the `secret` option. Use `GithubCredentials.fromPersonalAccessToken({ secret: 'MY_SECRET' })` to provide a custom secret name.
---
> fix(github)!: auto-queued pull requests are not getting merged

- .projen/tasks.json
- docs/api/javascript.md
- src/javascript/upgrade-dependencies.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/cdk8s/cdk8s-app-project-ts.test.ts
- test/javascript/upgrade-dependencies.test.ts
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/typescript/typescript.test.ts
- test/web/__snapshots__/nextjs-project.test.ts.snap
- test/web/__snapshots__/nextjs-ts-project.test.ts.snap
- test/web/__snapshots__/react-project.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
Fixes https://github.com/projen/projen/issues/3921
BREAKING CHANGE: Deprecated versions will now be ignored from dependency upgrades. Use `includeDeprecatedVersions: true` to retain the previous behavior.
---
> fix(upgrade-dependencies)!: deprecated versions are not excluded from dependency upgrades

- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
Fixes #3962
`minNodeVersion` is supposed to define the version of `@types/node` that is installed. However when `minNodeVersion` is set to just a major version, e.g. `20` than this failed because `semver.parse("20")` fails.
Instead we use `semver.minVersion(minNodeVersion)` which makes sense because we definitely want the minimal version here.
---
> fix(typescript): `minNodeVersion` doesn't update `@types/node` when it's just a major version number

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-bundled-main.yml
- .github/workflows/upgrade-main.yml
- .projenrc.ts
`lru-cache` has dropped support for Node 18, and now requires Node 20 or higher.
When `projen` creates new projects that use jest, it pulls in `lru-cache` using the following dependency path:
```
jest > @jest/core > @jest/transform > @babel/core > @babel/helper-compilation-targets > lru-cache
```
That happens to install the newest `lru-cache` version, which no longer works on Node 18, and so our tests fail.
Bump our workflow Node to 20 to at least make our PR build pass again (should we use `lts/*` to be done with this periodic breakage?)
This means that `projen new typescript-app` will no longer work on Node 18.
I don't know if this should have bearing on projen's minimum Node version; I suppose *technically* not, and people with a working `package-lock` will be unaffected... but it …
> chore: bump workflow node version to 20

- docs/testing/index.md
- docusaurus/README.md
As reported [here](https://github.com/projen/projen/discussions/4049#discussion-7883067), they don't work. Not sure if they ever worked.
We will need to come up with a better local debugging flow. In the meantime remove instructions that don't work and waste people's time.
---
> chore(docs): remove outdated debugging instructions

- docs/api/projen.md
- src/task-model.ts
- src/task-runtime.ts
- test/cli.test.ts
Custom task definitions do not allow for bash-style variable expansion.
For example, we have a task definition that looks like this:
```json5
{
exec: 'prettier --write --ignore-unknown --loglevel=warn "$@"',
receiveArgs: true,
}
```
It expects to invoke `prettier` on a series of filenames to be expanded from `"$@"`. Normally in bash, this quoted variable expansion (`"$@")` would automatically wrap whitespace containing elements in single quotes to preserve whitespace. Without this behavior, filenames including whitespace would be split and interpreted as separate filename tokens.
Currently, if we invoke `npx projen <prettier task> src/foo\ bar.txt` prettier is incorrectly invoked on `src/foo` and `bar.txt` as separate tokens because projen does not preserve whitespace in arguments.
This …
> feat(task-runtime): support bash-like quoted argument expansion in task arguments 

- docs/api/release.md
- src/release/release-trigger.ts
- test/release/release-trigger.test.ts
- test/release/release.test.ts
I want to be able to trigger a release only by starting a workflow on GitHub, and nothing else.
The `manual` trigger implies a task I need to run from a working copy, but I want just the scheduled job, except it runs whenever I choose and not on an actual schedule.
---
> feat(release): `ReleaseTrigger.workflowDispatch`

- src/release/bump-version.ts
- test/version.test.ts
The `nextVersionCommand` script should have full control over whether a version bump gets executed or not, but currently there is logic that decides that if there are 0 commits since the last tag, the bump will always be skipped.
Change that to take the output of the `nextVersionCommand` script into account.
---
> fix(bump): output of nextVersionCommand is ignored if there are 0 new commits

- docs/api/github.md
- src/github/github.ts
This causes confusion for users.
---
> chore(github): default value for `mergeQueue` is incorrectly documented as `true`

- docs/api/projen.md
- src/task.ts
- test/tasks/tasks.test.ts
We supported `updateStep()` and `removeStep()` already on Tasks, but not `insertStep()` yet. Add that as well.
---
> feat: add steps to a task

- docs/api/github.md
- src/github/workflows.ts
- test/github/github-workflow.test.ts
Fixes #4135 
It is currently not possible to set `env` for GithubWorkflows at a global scope, other than:
```
const workflow = new GithubWorkflow(project.github!, 'test-workflow')
workflow.file?.patch(
JsonPatch.add('/env', {
FOO: 'bar',
})
);
```
This PR makes it possible to pass the `env` object as an option at initialization, to set it on workflow level, which is useful for environment variables that are applicable to all jobs. e.g. `NODE_VERSION`
```
new GithubWorkflow(project.github!, 'test-workflow', { env: { FOO: "bar" } });
``` 
---
> fix(github): allow setting workflow env at global scope

- test/jsii/jsii.test.ts
The combination of `jsii-rosetta` 5.4 and `jsii-pacmak` >= 1.110 does not install anymore (since packmak requires >= 5.5)
Remove the 5.4 line from our tests (because they fail) and add 5.7 and 5.8.
---
> chore: fix tests by dropping jsii support

- src/github/private/util.ts
- test/github/expressions.test.ts
> This is extracted from another PR where I ended up changing the
structure so I don't need it anymore, but I think a function like this is useful in general so I want to commit it anyway.
Converting arbitrary data to GitHub Actions format reliably is not super hard but it's not extremely trivial either, especially once we get into things like quoting strings and transferring data like arrays.
This adds a helper function that takes away the guesswork and renders a GitHub Actions expression that will evaluate to the given JavaScript value.
---
> chore: add helper to convert arbitrary JSON to GitHub expressions

- docs/api/awscdk.md
- docs/api/cdk.md
- docs/api/cdk8s.md
- docs/api/cdktf.md
- docs/api/javascript.md
- docs/api/projen.md
- docs/api/release.md
- docs/api/typescript.md
- docs/api/web.md
- docs/quick-starts/typescript/hello-world/index.md
- src/release/bump-type.ts
- src/release/bump-version.ts
- src/release/commit-tag-version.ts
- src/release/release.ts
- src/version.ts
- test/version.test.ts
Previously, when `nextVersionCommand` was specified it would need to entirely determine the bump decision, or it was not specified and the bump decision was fully left to `commit-and-tag-version`.
If we want to use `nextVersionCommand` to do "the default action but occasionally something else", it now need to do a bunch of work itself, like determining what "the default action even is", i.e., it would need to duplicate or invoke CATV.
This is a place for user code to affect the versioning decision. For example, in monorepos we would use this to copy the version of other packages, or for workflows that test installation we would inject fake version numbers here, or we would force major version bumps when certain files have changed, or copy the version number from a data file. There are …
> feat: `nextVersionCommand` can look at and modify existing bump decision

- src/awscdk/awscdk-app-ts.ts
- test/awscdk/awscdk-app.test.ts
Fixes #4177
In #4134 we incorrectly started using `runScriptCommand` to execute `ts-node`. But `runScriptCommand` is only for running scripts from `package.json` not to execute a binary like `ts-node`. Fix this by switching to the correct exec command for each package manager.
---
> fix(awscdk): incorrect default app commands in AWS CDK app

- src/awscdk/awscdk-app-ts.ts
- test/awscdk/awscdk-app.test.ts
This PR changes the AWS CDK TypeScript app to use `npx` instead of `yarn exec` for running ts-node, even when using Yarn as the package manager.
Fixes #4180
- Modified `src/awscdk/awscdk-app-ts.ts` to use `npx` instead of `yarn exec` for ts-node
- Updated corresponding tests in `test/awscdk/awscdk-app.test.ts`
There have been reported issues with `yarn exec` when running ts-node in AWS CDK TypeScript apps. Using `npx` provides a more consistent experience across different package managers. Although we cannot reproduce the reported issues, reverting back to how this was for the last >5 years seems like a reasonable option. Users can still define a custom app command of their choice. 
---
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> fix: use npx instead of yarn exec for ts-node in AWS CDK TypeScript apps

- src/awscdk/awscdk-app-ts.ts
- test/awscdk/awscdk-app.test.ts
Similar to yarn, use npx instead of pnpm exec for ts-node execution to ensure consistent behavior and address potential issues. Relates to #4180.
---
> fix(awscdk): use npx for ts-node execution with pnpm

- .eslintrc.json
- docs/api/javascript.md
- src/_resolve.ts
- src/javascript/eslint.ts
- src/javascript/node-package.ts
- test/__snapshots__/integ.test.ts.snap
- test/cdk/__snapshots__/jsii.test.ts.snap
- test/javascript/__snapshots__/eslint.test.ts.snap
- test/jsii/__snapshots__/jsii.test.ts.snap
- test/typescript/__snapshots__/typescript.test.ts.snap
- test/web/__snapshots__/react-ts-project.test.ts.snap
With eslint v8 all "formatting" rules have been deprecated and moved into a separate plugin called `@stylistic`. In future all formatting rules will be removed from eslint. Some rules have been removed already and in projen we moved them over to use the `@stylistic` version. However not all rules have been updated and as it turns out projen's and eslint's definition on what is formatting did not fully align. The PR also upgrades `@stylistic/eslint-plugin` to v3.
In this change projen is adopting eslint's definition of what a "formatting" rule is. As a consequence, it moves a number of rules to formatting and vice versa. All formatting rules now use the `@stylistic` version. Notably, any configurations using prettier do not get any formatting rules (as they are delegated to prettier), but …
> fix(eslint): make lint vs formatting rules consistent with official eslint definition

- docs/api/javascript.md
- src/javascript/eslint.ts
- test/javascript/eslint.test.ts
This PR exposes the underlying config file of the Eslint component as a public property, allowing direct manipulation of the eslint configuration file.
The change:
- Adds a new `file` property to the Eslint class that provides access to the underlying ObjectFile
- Updates API documentation to reflect this new property
- Adds a test to verify the functionality works as expected
This enhancement makes it easier to customize eslint configuration through direct file manipulation when needed.
---
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
> feat(eslint): expose underlying config file as public property

- docs/api/projen.md
- src/release/bump-version.ts
- src/util.ts
- src/version.ts
- test/python/poetry.test.ts
We are seeing some weird behavior around considering commits with breaking changes in a monorepo context as part of the wrong package. The logging of the bump task isn't up to snuff to debug this issue. Add more logging to try to figure out what's going on.
---
> fix(bump): log more information during the bumping process

- src/javascript/node-package.ts
- src/javascript/util.ts
- test/javascript/node-project.test.ts
- test/javascript/util.test.ts
This PR has two changes that I think are important to improving the usability of the `yarn run ca:login` task.
Requiring that the `ca:login` task sees a `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variable means that the task does not work for local developers who use other methods to log in to AWS. This breaks if you are running in a Kubernetes Pod that is using web identity access files. This breaks if you are operating using AWS SSO logins. This breaks if you simply have your credentials hard-coded in your AWS config file.
I propose removing this requirement because it's just too explicit.
We have hundreds of CodeArtifact repositories that use a `.` in their name - ie `"myrepo.git"`.. it's completely valid to have a `.` in the name of a CodeArtifact repository, yet the …
> fix(javascript): remove requiredEnv and dot-exclusion from codeartifact login task

- docs/api/circleci.md
- src/circleci/circleci.ts
- src/circleci/model.ts
- test/circleci/__snapshots__/circleci.test.ts.snap
- test/circleci/circleci.test.ts
Support the circleci_ip_ranges property from the CircleCI config reference
https://circleci.com/docs/configuration-reference/#circleciipranges
> feat(circleci): support `circleciIpRanges` in CircleCI Job

- docs/api/typescript.md
- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
fixes #4284
As outlined in the linked issue, the inline compiler options should not be wrapped in an extra `compilerOptions` property.
See also the [ts-docs for the tsconfig option](https://kulshekhar.github.io/ts-jest/docs/getting-started/options/tsconfig/#inline-compiler-options).
---
> fix(typescript): ts-jest inline compiler options type

- .github/workflows/build.yml
- projenrc/windows-build.ts
Build times on Windows have crept up to about an hour and roughly 5x slower compared to the Ubuntu build. There is literature [1] that windows build on GitHub have bad I/O performance and that the D: drive should be faster. 
This change moves the temp directory and the yarn cache to the D: drive. Overall this reduces the build time by 40 min down to 17 min (compared to 11 min on Ubuntu). So much better!
[1] https://chadgolden.com/blog/github-actions-hosted-windows-runners-slower-than-expected-ci-and-you
---
> chore: move CI workloads to D: drive on windows build to improve performance

- docs/introduction/getting-started.md
import { typescript } from 'projen';
const project = new typescript.TypeScriptProject({
// ...
});
Updated to this because of  syntax error.
Fixes #
---
> chore(docs): fix syntax error in getting-started.md

- docs/api/javascript.md
- src/javascript/jest.ts
- src/typescript/typescript.ts
- test/typescript/typescript.test.ts
Install ts-jest 29 when Jest's major is higher than 29
Affects only if jest version is explicitly set. Newly initialized project gets both version correctly as latest which works.
Fixes #4308
---
> feat: support for Jest 30 with Typescript

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- docs/api/awscdk.md
- docs/api/cdk.md
- docs/api/cdk8s.md
- docs/api/cdktf.md
- docs/api/javascript.md
- docs/api/typescript.md
- docs/api/web.md
- src/javascript/node-project.ts
- test/__snapshots__/inventory.test.ts.snap
- test/javascript/node-project.test.ts
Upgrades codecov/codecov-action from v4 to v5 and enables OIDC authentication by default for enhanced security.
- Upgrade codecov action to v5 in build and release workflows
- Add id-token: write permissions for OIDC auth
- Enable use_oidc: true by default when no token secret is provided
- Update documentation to reflect OIDC as default auth method
- Refactor id-token permission logic to account for codecov OIDC usage
- Update tests to reflect v5 action usage
Resolves #4344 
---
> feat: upgrade codecov action to v5 with OIDC authentication

- docs/api/cdk.md
- docs/api/release.md
- docs/publishing/publisher-component.md
- docs/publishing/trusted-publishing.md
- src/release/publisher.ts
- test/release/release.test.ts
Add support for NuGet trusted publishing similar to existing PyPI implementation.
- **Add trusted publishing options** to  interface
- **Update  method** to support OIDC authentication with proper permissions
- **Add comprehensive test coverage** for trusted publishing workflow generation
- **Update documentation** with setup instructions and migration guide
- **Improve trusted publishing docs** by consolidating redundant "How It Works" sections
- Secure authentication using OIDC tokens instead of long-lived API keys
- Automatic permission setup with `id-token: write` when trusted publishing is enabled
- Flexible configuration allowing custom secret names for the NuGet username
- Backward compatibility - existing API key-based publishing continues to work
```typescript …
```
> feat: add NuGet trusted publishing support

- src/release/publisher.ts
- test/release/publisher-trusted-publishing.test.ts
This PR adds validation to prevent conflicting authentication methods when trusted publishing is enabled for npm, NuGet, and PyPI publishers.
- Added validation in publishToNpm() to prevent using npmTokenSecret with trustedPublishing
- Added validation in publishToNuget() to prevent using nugetApiKeySecret with trustedPublishing  
- Added validation in publishToPyPi() to prevent using twineUsernameSecret/twinePasswordSecret with trustedPublishing
- Added comprehensive test coverage for all validation scenarios
Trusted publishing uses OIDC tokens for authentication, making traditional tokens/credentials unnecessary and potentially confusing. This validation provides clear error messages to guide users toward the correct configuration.
--- …
> feat(release): validate trusted publishing configurations
